return {
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageConcrete+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{552625113732, --[[ModItemBuildingTemplate StorageConcrete+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{524186023275, --[[ModItemBuildingTemplate StorageConcrete+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{227793795216, --[[ModItemBuildingTemplate StorageConcrete+ display_name]] "Betonlager+"},
	'display_name_pl', T{387157272719, --[[ModItemBuildingTemplate StorageConcrete+ display_name_pl]] "Betonlager"},
	'description', T{639126670381, --[[ModItemBuildingTemplate StorageConcrete+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/concrete_storage.tga",
	'build_pos', 3,
	'entity', "StorageDepotSmall_03",
	'encyclopedia_image', "UI/Encyclopedia/ConcreteDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Concrete",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageElectronics+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{656054314868, --[[ModItemBuildingTemplate StorageElectronics+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{343431464562, --[[ModItemBuildingTemplate StorageElectronics+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{325439729767, --[[ModItemBuildingTemplate StorageElectronics+ display_name]] "Elektroniklager+"},
	'display_name_pl', T{258443774354, --[[ModItemBuildingTemplate StorageElectronics+ display_name_pl]] "Elektroniklager"},
	'description', T{875953845223, --[[ModItemBuildingTemplate StorageElectronics+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/electronics_storage.tga",
	'build_pos', 7,
	'entity', "StorageDepotSmall_08",
	'encyclopedia_image', "UI/Encyclopedia/ElectronicsDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Electronics",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageFood+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{597098715393, --[[ModItemBuildingTemplate StorageFood+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{608790222951, --[[ModItemBuildingTemplate StorageFood+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{512400858194, --[[ModItemBuildingTemplate StorageFood+ display_name]] "Nahrungsspeicher+"},
	'display_name_pl', T{865756854912, --[[ModItemBuildingTemplate StorageFood+ display_name_pl]] "Nahrungsspeicher"},
	'description', T{470136538911, --[[ModItemBuildingTemplate StorageFood+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/food_storage.tga",
	'build_pos', 4,
	'entity', "StorageDepotSmall_04",
	'encyclopedia_image', "UI/Encyclopedia/FoodDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Food",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageFuel+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{910512122256, --[[ModItemBuildingTemplate StorageFuel+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{890365313049, --[[ModItemBuildingTemplate StorageFuel+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{626170574201, --[[ModItemBuildingTemplate StorageFuel+ display_name]] "Treibstofflager+"},
	'display_name_pl', T{621644535542, --[[ModItemBuildingTemplate StorageFuel+ display_name_pl]] "Treibstofflager"},
	'description', T{470360092292, --[[ModItemBuildingTemplate StorageFuel+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/fuel_storage.tga",
	'build_pos', 9,
	'entity', "StorageDepotSmall_06",
	'encyclopedia_image', "UI/Encyclopedia/FuelDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Fuel",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageMachineParts+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{847061285489, --[[ModItemBuildingTemplate StorageMachineParts+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{498350283327, --[[ModItemBuildingTemplate StorageMachineParts+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{390904998057, --[[ModItemBuildingTemplate StorageMachineParts+ display_name]] "Maschinenteilelager+"},
	'display_name_pl', T{934933137100, --[[ModItemBuildingTemplate StorageMachineParts+ display_name_pl]] "Maschinenteilelager"},
	'description', T{172296369394, --[[ModItemBuildingTemplate StorageMachineParts+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/machine_parts_storage.tga",
	'build_pos', 8,
	'entity', "StorageDepotSmall_05",
	'encyclopedia_image', "UI/Encyclopedia/MachinePartsDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"MachineParts",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageMetals+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{590617665857, --[[ModItemBuildingTemplate StorageMetals+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{355802239563, --[[ModItemBuildingTemplate StorageMetals+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{831000368036, --[[ModItemBuildingTemplate StorageMetals+ display_name]] "Metalllager+"},
	'display_name_pl', T{136180345912, --[[ModItemBuildingTemplate StorageMetals+ display_name_pl]] "Metalllager"},
	'description', T{145526536780, --[[ModItemBuildingTemplate StorageMetals+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/metal_storage.tga",
	'build_pos', 2,
	'entity', "StorageDepotSmall_02",
	'encyclopedia_image', "UI/Encyclopedia/MetalsDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Metals",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageMysteryResource+",
	'template_class', "MysteryDepot",
	'pin_rollover_hint', T{741524592829, --[[ModItemBuildingTemplate StorageMysteryResource+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{129998039342, --[[ModItemBuildingTemplate StorageMysteryResource+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{470929180828, --[[ModItemBuildingTemplate StorageMysteryResource+ display_name]] "Geheimnisvolles Lager+"},
	'display_name_pl', T{949638340939, --[[ModItemBuildingTemplate StorageMysteryResource+ display_name_pl]] "Geheimnisvolles Lager"},
	'description', T{890677918316, --[[ModItemBuildingTemplate StorageMysteryResource+ description]] "Es ist sehr geheimnisvoll."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/mystery_resource_storage.tga",
	'build_pos', 12,
	'entity', "StorageDepotSmall_10",
	'encyclopedia_exclude', true,
	'encyclopedia_image', "UI/Encyclopedia/MetalsDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"MysteryResource",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StoragePolymers+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{306739024860, --[[ModItemBuildingTemplate StoragePolymers+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{545222835158, --[[ModItemBuildingTemplate StoragePolymers+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{224939348092, --[[ModItemBuildingTemplate StoragePolymers+ display_name]] "Polymer-Lager+"},
	'display_name_pl', T{416129436468, --[[ModItemBuildingTemplate StoragePolymers+ display_name_pl]] "Polymer-Lager"},
	'description', T{241254886096, --[[ModItemBuildingTemplate StoragePolymers+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/polymers_storage.tga",
	'build_pos', 6,
	'entity', "StorageDepotSmall_01",
	'encyclopedia_image', "UI/Encyclopedia/PolymersDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Polymers",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageRareMetals+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{196237200622, --[[ModItemBuildingTemplate StorageRareMetals+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{502879348319, --[[ModItemBuildingTemplate StorageRareMetals+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{998381805313, --[[ModItemBuildingTemplate StorageRareMetals+ display_name]] "Edelmetalllager+"},
	'display_name_pl', T{824504035730, --[[ModItemBuildingTemplate StorageRareMetals+ display_name_pl]] "Edelmetalllager"},
	'description', T{286943160713, --[[ModItemBuildingTemplate StorageRareMetals+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/rare_metals_storage.tga",
	'build_pos', 5,
	'entity', "StorageDepotSmall_07",
	'encyclopedia_image', "UI/Encyclopedia/RareMetalsDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"PreciousMetals",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "UniversalStorageDepot+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{594322232300, --[[ModItemBuildingTemplate UniversalStorageDepot+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{933354388434, --[[ModItemBuildingTemplate UniversalStorageDepot+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{547382600773, --[[ModItemBuildingTemplate UniversalStorageDepot+ display_name]] "Universallager+"},
	'display_name_pl', T{259426228168, --[[ModItemBuildingTemplate UniversalStorageDepot+ display_name_pl]] "Universallager"},
	'description', T{843398480089, --[[ModItemBuildingTemplate UniversalStorageDepot+ description]] "Bietet Platz zur Lagerung von  Einheiten jeder transportierbaren Ressource. Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/universal_storage.tga",
	'entity', "StorageDepot",
	'encyclopedia_image', "UI/Encyclopedia/UniversalDepot.tga",
	'build_shortcut1', "U",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 100000,
	'switch_fill_order', false,
	'fill_group_idx', 9,
}),
}
