return {
PlaceObj('ModItemBuildingTemplate', {
	'Id', "TubularHouse",
	'template_class', "Apartments",
	'pin_on_start', true,
	'pin_obvious_blink', true,
	'construction_cost_Concrete', 7000,
	'construction_cost_Metals', 1000,
	'construction_cost_Polymers', 2000,
	'is_tall', true,
	'dome_required', true,
	'lights_on_during_placement', true,
	'maintenance_resource_type', "Concrete",
	'display_name', T(232179993984, --[[ModItemBuildingTemplate TubularHouse display_name]] "Glass House"),
	'display_name_pl', T(152395068608, --[[ModItemBuildingTemplate TubularHouse display_name_pl]] "Glass Houses"),
	'description', T(196759429199, --[[ModItemBuildingTemplate TubularHouse description]] "Cylindrical-shaped house with much glass. By the way it's a fake parquet if you were wondering. Made of Polymers. And the tree too."),
	'build_category', "Habitats",
	'display_icon', "UI/TubularHouse.png",
	'entity', "TubularHouse",
	'dome_comfort', 1000,
	'electricity_consumption', 3000,
	'capacity', 8,
	'rest_duration', 120000,
}),
PlaceObj('ModItemEntity', {
	'name', "TubularHouse",
	'comment', "Test",
	'entity_name', "TubularHouse",
	'import', "Entities/TubularHouse.ent",
}),
}
