botanist
engineer
geologist
medic
scientist
security
none

local workplaces = {
	AdvancedStirlingGenerator = "none",
	Apartments = "none",
	Arcology = "none",
	AtomicBattery = "none",
	AutomaticMetalsExtractor = "none",
	Battery_WaterFuelCell = "none",
	CarbonateProcessor = "none",
	ConcretePlant = "none",
	CoreHeatConvector = "none",
	DefenceTower = "none",
	DroneHub = "none",
	ElectricityStorage = "none",
	ForestationPlant = "none",
	FuelFactory = "none",
	GHGFactory = "none",
	HangingGardens = "none",
	JumperShuttleHub = "none",
	LandingPad = "none",
	LargeWaterTank = "none",
	LivingQuarters = "none",
	LivingQuarters_Small = "none",
	MagneticFieldGenerator = "none",
	MartianUniversity = "none",
	MDSLaser = "none",
	MetalsRefinery = "none",
	MoistureVaporator = "none",
	MOXIE = "none",
	Nursery = "none",
	OpenAirGym = "none",
	OpenCity = "none",
	OpenFarm = "none",
	OxygenTank = "none",
	OxygenTank_Large = "none",
	OxygenTankLarge = "none",
	Playground = "none",
	RareMetalsRefinery = "none",
	RechargeStation = "none",
	RegolithExtractor = "none",
	Sanatorium = "none",
	School = "none",
	SensorTower = "none",
	ShuttleHub = "none",
	SmartHome = "none",
	SmartHome_Small = "none",
	SolarArray = "none",
	SolarPanel = "none",
	SolarPanelBig = "none",
	StirlingGenerator = "none",
	SubsurfaceHeater = "none",
	TaiChiGarden = "none",
	TradePad = "none",
	TriboelectricScrubber = "none",
	Tunnel = "none",
	WasteRockProcessor = "none",
	WaterExtractor = "none",
	WaterTank = "none",
	WaterTankLarge = "none",
	WindTurbine = "none",
	WindTurbine_Large = "none",
}
