return {
PlaceObj("ModItemBuildingTemplate", {
  "name", "GeoscapeDome*",
  "template_class", "GeoscapeDome",
  "pin_summary1", T({5016, "<GetColonistCount><icon_Colonist_small>"}),
  "pin_on_start", true,
  "construction_cost_Concrete", 400000,
  "construction_cost_Metals", 200000,
  "construction_cost_Polymers", 300000,
  "construction_entity", "DomeGeoscapeConstruction",
  "build_points", 120000,
  "is_tall", true,
  "construction_site_applies_height_surfaces", true,
  "dome_forbidden", true,
  "maintenance_resource_type", "Polymers",
  "maintenance_resource_amount", 3000,
  "display_name", "Geoscape Dome*",
  "display_name_pl","Geoscape Domes",
  "description", "A slice of Earth on Mars, this Dome increases the Comfort of all Residences within. It also increases the Sanity of its inhabitants every Sol.",
  "build_category", "Wonders",
  "display_icon", "UI/Icons/Buildings/geoscape_dome.tga",
  "build_pos", 3,
  "entity", "DomeGeoscape",
  "dome_comfort", 25000,
  "encyclopedia_image", "UI/Encyclopedia/GeoscapeDome.tga",
  "demolish_sinking", range(0, 0),
  "demolish_debris", 0,
  "electricity_consumption", 40000,
  "air_consumption", 0,
  "DailySanityRecoverDome", 5000,
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "ArtificialSun*",
  "template_class", "ArtificialSun",
  "construction_cost_Concrete", 200000,
  "construction_cost_Metals", 300000,
  "construction_cost_Polymers", 300000,
  "build_points", 120000,
  "is_tall", true,
  "dome_forbidden", true,
  "maintenance_resource_type", "Polymers",
  "maintenance_resource_amount", 3000,
  "display_name", "Artificial Sun*",
  "display_name_pl", "Artificial Suns",
  "description", "This marvel of Martian engineering produces colossal amounts of Power. It provides light for nearby solar panels during the night in addition to heating the surrounding area. Consumes vast amounts of Water on startup.",
  "build_category", "Wonders",
  "display_icon", "UI/Icons/Buildings/artificial_sun.tga",
  "entity", "ArtificialSun",
  "encyclopedia_image", "UI/Encyclopedia/ArtificialSun.tga",
  "label1", "OutsideBuildings",
  "palettes", "Blue_White_Black",
  "demolish_sinking", range(15, 20),
  "demolish_tilt_angle", range(300, 1800),
  "demolish_debris", 55,
  "water_consumption", 0,
  "air_consumption", 0,
  "electricity_production", 1000000,
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "MoholeMine*",
  "template_class", "MoholeMine",
  "resource_produced1", "Metals",
  "max_storage1", 50000,
  "production_per_day1", 50000,
  "resource_produced2", "PreciousMetals",
  "max_storage2", 50000,
  "production_per_day2", 20000,
  "resource_produced3", "WasteRock",
  "max_storage3", 50000,
  "stockpile_class3", "WasteRockStockpile",
  "construction_cost_Concrete", 400000,
  "construction_cost_Metals", 100000,
  "construction_cost_MachineParts", 300000,
  "build_points", 120000,
  "dome_forbidden", true,
  "maintenance_resource_type", "MachineParts",
  "maintenance_resource_amount", 3000,
  "display_name", "Mohole Mine*",
  "display_name_pl", "Mohole Mines",
  "description", "Mining deep into the crust of Mars, the Mohole Mine produces Metals, Rare Metals and Waste Rock, while heating the surrounding area.",
  "build_category", "Wonders",
  "display_icon", "UI/Icons/Buildings/mohole_mine.tga",
  "entity", "MoholeMine",
  "encyclopedia_image", "UI/Encyclopedia/MoholeMine.tga",
  "label1", "OutsideBuildings",
  "palettes", "MoholeMine",
  "demolish_sinking", range(0, 0),
  "demolish_tilt_angle", range(0, 0),
  "penalty_heat", 182,
  "penalty_pct", 51,
  "electricity_consumption", 40000,
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "OmegaTelescope*",
  "template_class", "OmegaTelescope",
  "construction_cost_Concrete", 400000,
  "construction_cost_Metals", 300000,
  "construction_cost_Electronics", 300000,
  "build_points", 120000,
  "dome_forbidden", true,
  "maintenance_resource_type", "Electronics",
  "maintenance_resource_amount", 3000,
  "display_name", "Omega Telescope*",
  "display_name_pl","Omega Telescopes",
  "description", "Peering beyond the veil of the unknown, this radio telescope gives access to new Breakthrough Technologies and boosts overall Research.",
  "build_category", "Wonders",
  "display_icon", "UI/Icons/Buildings/omega_telescope.tga",
  "entity", "RadioDish",
  "encyclopedia_image", "UI/Encyclopedia/OmegaTelescope.tga",
  "label1", "OutsideBuildings",
  "palettes", "PolumerPlant",
  "demolish_sinking", range(5, 10),
  "demolish_tilt_angle", range(300, 720),
  "electricity_consumption", 80000,

}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "ProjectMorpheus*",
  "template_class", "ProjectMorpheus",
  "construction_cost_Concrete", 200000,
  "construction_cost_Metals", 400000,
  "construction_cost_Electronics", 300000,
  "build_points", 120000,
  "is_tall", true,
  "dome_forbidden", true,
  "maintenance_resource_type", "Electronics",
  "maintenance_resource_amount", 3000,
  "display_name", "Project Morpheus*",
  "display_name_pl", "Projects Morpheus",
  "description", "With our improved understanding of the human brain we created Project Morpheus. The device uses a combination of psychosomatic triggers and suggestopedic methodology to stimulate the development of new Perks in adult Colonists.",
  "build_category", "Wonders",
  "display_icon", "UI/Icons/Buildings/project_morpheus.tga",
  "build_pos", 2,
  "entity", "ProjectMorpheus",
  "encyclopedia_image", "UI/Encyclopedia/ProjectMorpheus.tga",
  "label1", "OutsideBuildings",
  "palettes", "Morpheus",
  "demolish_sinking", range(5, 10),
  "demolish_debris", 75,
  "electricity_consumption", 110000,
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "SpaceElevator*",
  "template_class", "SpaceElevator",
  "pin_on_start", true,
  "construction_cost_Concrete", 400000,
  "construction_cost_Metals", 200000,
  "construction_cost_Polymers", 150000,
  "construction_cost_MachineParts", 150000,
  "build_points", 120000,
  "dome_forbidden", true,
  "use_demolished_state", true,
  "maintenance_resource_type", "MachineParts",
  "maintenance_resource_amount", 3000,
  "display_name", "Space Elevator*",
  "display_name_pl", "Space Elevators",
  "description", "A faster way to reach space, the Elevator speeds up cargo shipments to orbit. Exports Rare Metals to Earth and offers resupply materials and prefabs at a discount.",
  "build_category", "Wonders",
  "display_icon", "UI/Icons/Buildings/space_elevator.tga",
  "entity", "SpaceElevator",
  "encyclopedia_image", "UI/Encyclopedia/SpaceElevator.tga",
  "label1", "OutsideBuildings",
  "palettes", "SpaceElevator",
  "max_storage_per_resource", 100000000,
  "storable_resources", {"Concrete", "Metals", "Polymers", "Food", "Electronics", "MachineParts"},
  "electricity_consumption", 40000,
  "cargo_capacity", 80000,
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "TheExcavator*",
  "template_class", "TheExcavator",
  "construction_cost_Concrete", 100000,
  "construction_cost_Metals", 300000,
  "construction_cost_MachineParts", 200000,
  "build_points", 120000,
  "dome_forbidden", true,
  "force_extend_bb_during_placement_checks", 12000,
  "maintenance_resource_type", "MachineParts",
  "maintenance_resource_amount", 3000,
  "display_name","The Excavator*",
  "display_name_pl", "The Excavators",
  "description", "Using advanced extraction technology, allows for production of Concrete directly from the Martian soil without the requirement for a deposit.",
  "build_category", "Wonders",
  "display_icon", "UI/Icons/Buildings/the_excavator.tga",
  "build_pos", 2,
  "entity", "Excavator",
  "encyclopedia_image", "UI/Encyclopedia/TheExcavator.tga",
  "label1", "OutsideBuildings",
  "palettes","MoholeMine",
  "demolish_sinking", range(1, 5),
  "demolish_debris", 30,
  "electricity_consumption", 30000,
  "resource_produced1", "Concrete",
  "max_storage1", 50000,
  "production_per_day1", 50000,
  "resource_produced2", "WasteRock",
  "max_storage2", 50000,
  "stockpile_class2", "WasteRockStockpile",
}),

}
