return {
PlaceObj('ModItemBuildingTemplate', {
	'name', "Arcology+",
	'template_class', "Arcology",
	'pin_rollover_hint', T{500510952275, --[[ModItemBuildingTemplate Arcology+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{654998511859, --[[ModItemBuildingTemplate Arcology+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 80000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'is_tall', true,
	'dome_required', true,
	'dome_spot', "Spire",
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "Arcology_HomeCollective",
	'upgrade1_display_name', T{152099869764, --[[ModItemBuildingTemplate Arcology+ upgrade1_display_name]] "Heimatgemeinschaft"},
	'upgrade1_description', T{668186528690, --[[ModItemBuildingTemplate Arcology+ upgrade1_description]] "+<upgrade1_add_value_1> Service-Komfort"},
	'upgrade1_icon', "UI/Icons/Upgrades/home_collective_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_mod_label_1', "Arcology",
	'upgrade1_mod_prop_id_1', "service_comfort",
	'upgrade1_add_value_1', 60,
	'upgrade1_mod_label_2', "Kuppelkomfort+",
	'upgrade1_mod_prop_id_2', "dome_comfort",
	'upgrade1_add_value_2', 60,
	'upgrade1_mod_label_3', "Kol+",
	'upgrade1_mod_prop_id_3', "MaxColonistsPerRocket",
	'upgrade1_add_value_3', 50,
	'maintenance_resource_type', "Beton",
	'display_name', T{828347920027, --[[ModItemBuildingTemplate Arcology+ display_name]] "Arkologie+"},
	'display_name_pl', T{687561944557, --[[ModItemBuildingTemplate Arcology+ display_name_pl]] "Arkologie"},
	'description', T{443190513635, --[[ModItemBuildingTemplate Arcology+ description]] "Bietet Wohnraum für zahlreiche Kolonisten und gewährt viel Komfort."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/arcology.tga",
	'entity', "Arcology",
	'encyclopedia_image', "UI/Encyclopedia/Arcology.tga",
	'label1', "InsideBuildings",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(0, 0),
	'demolish_debris', 90,
	'spire_frame_entity', "ArcologyFrame",
	'electricity_consumption', 20000,
	'health_change', 20000,
	'sanity_change', 20000,
	'service_comfort', 99000,
	'comfort_increase', 20000,
	'capacity', 130,
	'rest_duration', 30000,
	'sanity_increase', 20000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Arcology+-",
	'template_class', "Arcology",
	'pin_rollover_hint', T{711856520896, --[[ModItemBuildingTemplate Arcology+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{135992215296, --[[ModItemBuildingTemplate Arcology+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 80000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "Arcology_HomeCollective",
	'upgrade1_display_name', T{513543356481, --[[ModItemBuildingTemplate Arcology+- upgrade1_display_name]] "Heimatgemeinschaft"},
	'upgrade1_description', T{803541862152, --[[ModItemBuildingTemplate Arcology+- upgrade1_description]] "+<upgrade1_add_value_1> Service-Komfort"},
	'upgrade1_icon', "UI/Icons/Upgrades/home_collective_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_mod_label_1', "Arcology",
	'upgrade1_mod_prop_id_1', "service_comfort",
	'upgrade1_add_value_1', 10,
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 4000,
	'display_name', T{925650677502, --[[ModItemBuildingTemplate Arcology+- display_name]] "Arkologie"},
	'display_name_pl', T{169452535309, --[[ModItemBuildingTemplate Arcology+- display_name_pl]] "Arkologie"},
	'description', T{436455479102, --[[ModItemBuildingTemplate Arcology+- description]] "Bietet Wohnraum für zahlreiche Kolonisten und gewährt viel Komfort."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/arcology.tga",
	'entity', "Arcology",
	'encyclopedia_image', "UI/Encyclopedia/Arcology.tga",
	'label1', "InsideBuildings",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(0, 0),
	'demolish_debris', 90,
	'spire_frame_entity', "ArcologyFrame",
	'electricity_consumption', 20000,
	'service_comfort', 60000,
	'comfort_increase', 4000,
	'capacity', 130,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "ArtificialSun",
	'template_class', "ArtificialSun",
	'pin_rollover_hint', T{633809766738, --[[ModItemBuildingTemplate ArtificialSun pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{863735241040, --[[ModItemBuildingTemplate ArtificialSun pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 2000,
	'construction_cost_Metals', 3000,
	'construction_cost_Polymers', 3000,
	'build_points', 120000,
	'instant_build', true,
	'is_tall', true,
	'dome_forbidden', true,
	'achievement', "BuiltArtificialSun",
	'use_demolished_state', false,
	'maintenance_resource_type', "Beton",
	'display_name', T{661525605218, --[[ModItemBuildingTemplate ArtificialSun display_name]] "Künstliche Sonne"},
	'display_name_pl', T{420182499287, --[[ModItemBuildingTemplate ArtificialSun display_name_pl]] "Künstliche Sonnen"},
	'description', T{796116125002, --[[ModItemBuildingTemplate ArtificialSun description]] "Dieses Wunder marsianischer Ingenieurskunst produziert gewaltige Mengen Strom. Sie erzeugt in dunklen Stunden Licht für nahe gelegene Solarkollektoren und beheizt die Umgebung. Verbraucht bei der Inbetriebnahme große Wassermengen."},
	'build_category', "Wonders",
	'display_icon', "UI/Icons/Buildings/artificial_sun.tga",
	'entity', "ArtificialSun",
	'encyclopedia_image', "UI/Encyclopedia/ArtificialSun.tga",
	'label1', "OutsideBuildings",
	'palettes', "ArtificialSun",
	'demolish_sinking', range(15, 20),
	'demolish_tilt_angle', range(300, 1800),
	'demolish_debris', 55,
	'water_consumption', 0,
	'air_consumption', 0,
	'electricity_production', 1000000,
	'max_water_charge', 500000,
	'effect_range', 20,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "CloningVats+-",
	'template_class', "CloningVats",
	'pin_rollover_hint', T{750130467657, --[[ModItemBuildingTemplate CloningVats+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{503996716461, --[[ModItemBuildingTemplate CloningVats+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Metals', 50000,
	'construction_cost_Polymers', 20000,
	'construction_cost_Electronics', 10000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 3000,
	'display_name', T{987320846667, --[[ModItemBuildingTemplate CloningVats+- display_name]] "Klonbehälter"},
	'display_name_pl', T{722586586905, --[[ModItemBuildingTemplate CloningVats+- display_name_pl]] "Klonbehälter"},
	'description', T{241044431578, --[[ModItemBuildingTemplate CloningVats+- description]] "Erschafft im Laufe der Zeit Klone. Geklonte Kolonisten wachsen und altern doppelt so schnell."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/cloning_vats.tga",
	'build_pos', 4,
	'entity', "CloningVats",
	'encyclopedia_image', "UI/Encyclopedia/CloningVats.tga",
	'label1', "InsideBuildings",
	'palettes', "CloningVats",
	'demolish_sinking', range(15, 20),
	'demolish_tilt_angle', range(300, 720),
	'demolish_debris', 85,
	'electricity_consumption', 30000,
	'enabled_shift_2', false,
	'enabled_shift_3', false,
	'max_workers', 6,
	'specialist', "medic",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "DefenceTower+",
	'template_class', "DefenceTower",
	'pin_rollover_hint', T{410759895795, --[[ModItemBuildingTemplate DefenceTower+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{112569867959, --[[ModItemBuildingTemplate DefenceTower+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Metals', 10000,
	'construction_cost_Electronics', 5000,
	'build_points', 500,
	'is_tall', true,
	'dome_forbidden', true,
	'use_demolished_state', false,
	'maintenance_resource_type', "Electronics",
	'maintenance_threshold_base', 50000,
	'display_name', T{347857013876, --[[ModItemBuildingTemplate DefenceTower+ display_name]] "Verteidigungsturm"},
	'display_name_pl', T{337379114670, --[[ModItemBuildingTemplate DefenceTower+ display_name_pl]] "Verteidigungstürme"},
	'description', T{313653362096, --[[ModItemBuildingTemplate DefenceTower+ description]] "Ein Verteidigungsgebäude mit Laserzielerfassung. Schützt nahe Gebäude vor Meteoriten. Kann feindliche Fahrzeuge auf extrem große Entfernungen angreifen."},
	'build_category', "Infrastructure",
	'display_icon', "UI/Icons/Buildings/defense_turret.tga",
	'build_pos', 12,
	'entity', "DefenceTurret",
	'show_range_all', true,
	'encyclopedia_exclude', true,
	'label1', "OutsideBuildings",
	'palettes', "DefenceTurret",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 85,
	'demolish_return_resources', false,
	'electricity_consumption', 10000,
	'protect_range', 65,
	'pitch_range', range(1200, 4800),
	'reload_time', 3000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "DroneFactory",
	'template_class', "DroneFactory",
	'pin_rollover_hint', T{759431446901, --[[ModItemBuildingTemplate DroneFactory pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{347413763294, --[[ModItemBuildingTemplate DroneFactory pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Metals', 2000,
	'construction_cost_Electronics', 1000,
	'build_points', 7000,
	'is_tall', true,
	'dome_forbidden', true,
	'upgrade1_id', "Arcology_HomeCollective",
	'upgrade1_display_name', T{220416887326, --[[ModItemBuildingTemplate DroneFactory upgrade1_display_name]] "No Workers needed"},
	'upgrade1_description', T{444302642815, --[[ModItemBuildingTemplate DroneFactory upgrade1_description]] "No Workers needed"},
	'upgrade1_icon', "UI/Icons/Upgrades/home_collective_01.tga",
	'upgrade1_mod_prop_id_1', "automation",
	'upgrade1_add_value_1', 1,
	'upgrade1_mod_prop_id_2', "auto_performance",
	'upgrade1_add_value_2', 150,
	'upgrade1_mod_prop_id_3', "max_workers",
	'upgrade1_mul_value_3', -100,
	'maintenance_resource_type', "Electronics",
	'display_name', T{397567013889, --[[ModItemBuildingTemplate DroneFactory display_name]] "Drohnenfabrik"},
	'display_name_pl', T{800040869348, --[[ModItemBuildingTemplate DroneFactory display_name_pl]] "Drohnenfabriken"},
	'description', T{200804065171, --[[ModItemBuildingTemplate DroneFactory description]] "Stellt Drohnen-Fertigbauten her, dank denen in Drohnen-Hubs Drohnen – die gehorsamen Arbeitskräfte der Kolonie – bestellt werden können. Wahrscheinlich keine Gefahr für die Menschheit."},
	'build_category', "Production",
	'display_icon', "UI/Icons/Buildings/workshop.tga",
	'build_pos', 4,
	'entity', "Workshop",
	'encyclopedia_image', "UI/Encyclopedia/DroneAssembler.tga",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "Outside_02",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(600, 1200),
	'demolish_debris', 85,
	'electricity_consumption', 10000,
	'max_workers', 3,
	'specialist', "engineer",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "DroneHub",
	'template_class', "DroneHub",
	'pin_rollover', T{814327706079, --[[ModItemBuildingTemplate DroneHub pin_rollover]] "<description><newline><newline>Aktueller Status: <DronesStatusText><newline>Drohnen<right>"},
	'pin_rollover_hint', T{752629641375, --[[ModItemBuildingTemplate DroneHub pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{782323479083, --[[ModItemBuildingTemplate DroneHub pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'pin_summary1', T{958410429713, --[[ModItemBuildingTemplate DroneHub pin_summary1]] "<DronesCount><image UI/Icons/res_drone.tga 800>"},
	'pin_on_start', true,
	'build_points', 2000,
	'instant_build', true,
	'is_tall', true,
	'dome_forbidden', true,
	'use_demolished_state', false,
	'maintenance_resource_type', "Keine Wartung",
	'maintenance_resource_amount', 0,
	'display_name', T{155216425437, --[[ModItemBuildingTemplate DroneHub display_name]] "Drohnen-Hub"},
	'display_name_pl', T{742221948817, --[[ModItemBuildingTemplate DroneHub display_name_pl]] "Drohnen-Hubs"},
	'description', T{763311238384, --[[ModItemBuildingTemplate DroneHub description]] "Kontrolliert Drohnen und teilt ihnen unterschiedliche Aufgaben zu."},
	'build_category', "Infrastructure",
	'display_icon', "UI/Icons/Buildings/drone_hub.tga",
	'build_pos', 4,
	'entity', "DroneHub",
	'show_range_all', true,
	'encyclopedia_image', "UI/Encyclopedia/DroneHub.tga",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "DroneHub",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(900, 1500),
	'demolish_debris', 85,
	'refund_on_salvage', false,
	'starting_drones', 30,
	'electricity_consumption', 0,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Fuel Refinery+",
	'template_class', "FuelFactory",
	'resource_produced1', "Fuel",
	'max_storage1', 300000,
	'production_per_day1', 100000,
	'pin_rollover_hint', T{428943948960, --[[ModItemBuildingTemplate Fuel Refinery+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{567713212430, --[[ModItemBuildingTemplate Fuel Refinery+ pin_rollover_hint_xbox]] "<image UI/Xbox/ButtonA.tga> View"},
	'construction_cost_Concrete', 5000,
	'construction_cost_Metals', 5000,
	'construction_cost_MachineParts', 5000,
	'build_points', 3000,
	'is_tall', true,
	'dome_forbidden', true,
	'upgrade1_id', "FuelFactory_Amplify",
	'upgrade1_display_name', T{492287754060, --[[ModItemBuildingTemplate Fuel Refinery+ upgrade1_display_name]] "Amplify"},
	'upgrade1_description', T{880599652314, --[[ModItemBuildingTemplate Fuel Refinery+ upgrade1_description]] "+<upgrade1_mul_value_1>% Production; + Consumption."},
	'upgrade1_icon', "UI/Icons/Upgrades/amplify_01.tga",
	'upgrade1_upgrade_cost_Polymers', 2000,
	'upgrade1_mod_label_1', "FuelFactory",
	'upgrade1_mod_prop_id_1', "production_per_day1",
	'upgrade1_mul_value_1', 25,
	'upgrade1_mod_label_2', "FuelFactory",
	'upgrade1_mod_prop_id_2', "electricity_consumption",
	'upgrade1_add_value_2', 10000,
	'use_demolished_state', false,
	'maintenance_resource_type', "MachineParts",
	'display_name', T{625494994606, --[[ModItemBuildingTemplate Fuel Refinery+ display_name]] "Fuel Refinery+"},
	'display_name_pl', T{581570306217, --[[ModItemBuildingTemplate Fuel Refinery+ display_name_pl]] "Fuel Refineries"},
	'description', T{899880764311, --[[ModItemBuildingTemplate Fuel Refinery+ description]] "Produces 100 Fuel instead of 12."},
	'build_category', "Production",
	'display_icon', "UI/Icons/Buildings/fuel_rafinery.tga",
	'build_pos', 9,
	'entity', "FuelRefinery",
	'encyclopedia_image', "UI/Encyclopedia/FuelRefinery.tga",
	'entity2', "FuelRefineryChrome",
	'entitydlc2', "dde",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "FuelFactory",
	'demolish_sinking', range(1, 5),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 80,
	'demolish_return_resources', false,
	'refund_on_salvage', false,
	'electricity_consumption', 5000,
	'water_consumption', 0,
	'air_consumption', 0,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "FusionReactor+",
	'template_class', "FusionReactor",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{181876352010, --[[ModItemBuildingTemplate FusionReactor+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{306322766565, --[[ModItemBuildingTemplate FusionReactor+ pin_rollover_hint_xbox]] "<image UI/Xbox/ButtonA.tga> View"},
	'construction_cost_Concrete', 40000,
	'construction_cost_Polymers', 20000,
	'construction_cost_Electronics', 20000,
	'build_points', 15000,
	'instant_build', true,
	'dome_forbidden', true,
	'upgrade1_id', "FusionReactor_Autoregulator",
	'upgrade1_display_name', T{170861113581, --[[ModItemBuildingTemplate FusionReactor+ upgrade1_display_name]] "Autoregulator"},
	'upgrade1_description', T{840761336941, --[[ModItemBuildingTemplate FusionReactor+ upgrade1_description]] "Reduces Workplaces by <abs(upgrade1_add_value_1)>."},
	'upgrade1_icon', "UI/Icons/Upgrades/autoregulator_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_mod_label_1', "FusionReactor",
	'upgrade1_mod_prop_id_1', "max_workers",
	'upgrade1_add_value_1', -2,
	'upgrade2_id', "FusionReactor_EternalFusion",
	'upgrade2_display_name', T{648505726867, --[[ModItemBuildingTemplate FusionReactor+ upgrade2_display_name]] "Eternal Fusion"},
	'upgrade2_description', T{661262624482, --[[ModItemBuildingTemplate FusionReactor+ upgrade2_description]] "This building no longer requires Workers and operates at <upgrade2_add_value_2> Performance."},
	'upgrade2_icon', "UI/Icons/Upgrades/eternal_fusion_01.tga",
	'upgrade2_upgrade_cost_Polymers', 10000,
	'upgrade2_mod_prop_id_1', "automation",
	'upgrade2_add_value_1', 1,
	'upgrade2_mod_prop_id_2', "auto_performance",
	'upgrade2_add_value_2', 150,
	'upgrade2_mod_prop_id_3', "max_workers",
	'upgrade2_mul_value_3', -100,
	'maintenance_resource_type', "Electronics",
	'maintenance_resource_amount', 3000,
	'display_name', T{906430284111, --[[ModItemBuildingTemplate FusionReactor+ display_name]] "FusionReactor"},
	'display_name_pl', T{265779153923, --[[ModItemBuildingTemplate FusionReactor+ display_name_pl]] "FusionReactors"},
	'description', T{970505716888, --[[ModItemBuildingTemplate FusionReactor+ description]] "Generates 20K Watts instead of 200."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/fusion_reactor.tga",
	'build_pos', 5,
	'entity', "FusionReactor",
	'encyclopedia_image', "UI/Encyclopedia/FusionReactor.tga",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "UniversalExtractor",
	'demolish_sinking', range(10, 20),
	'demolish_tilt_angle', range(300, 600),
	'electricity_production', 20000000,
	'max_workers', 8,
	'specialist', "engineer",
	'automation', 5,
	'auto_performance', 1,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "GeoscapeDome+",
	'template_class', "GeoscapeDome",
	'pin_rollover_hint', T{766957247404, --[[ModItemBuildingTemplate GeoscapeDome+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{564158641803, --[[ModItemBuildingTemplate GeoscapeDome+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'pin_summary1', T{363417393680, --[[ModItemBuildingTemplate GeoscapeDome+ pin_summary1]] "<GetColonistCount><image UI/Icons/res_colonist.tga 800>"},
	'pin_on_start', true,
	'construction_cost_Concrete', 400000,
	'construction_cost_Metals', 200000,
	'construction_cost_Polymers', 300000,
	'construction_entity', "DomeGeoscapeConstruction",
	'build_points', 120000,
	'is_tall', true,
	'construction_site_applies_height_surfaces', true,
	'dome_forbidden', true,
	'achievement', "FirstDome",
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 3000,
	'display_name', T{242159070505, --[[ModItemBuildingTemplate GeoscapeDome+ display_name]] "Geoscape-Kuppel"},
	'display_name_pl', T{318289179948, --[[ModItemBuildingTemplate GeoscapeDome+ display_name_pl]] "Geoscape-Kuppeln"},
	'description', T{887217054637, --[[ModItemBuildingTemplate GeoscapeDome+ description]] "Ein Stück Erde auf dem Mars. Diese Kuppel erhöht den Komfort aller darin liegenden Wohnorte. Außerdem wird die Besonnenheit der Bewohner mit jedem Sol erhöht."},
	'build_category', "Domes",
	'display_icon', "UI/Icons/Buildings/geoscape_dome.tga",
	'build_pos', 6,
	'entity', "DomeGeoscape",
	'dome_comfort', 25000,
	'encyclopedia_image', "UI/Encyclopedia/GeoscapeDome.tga",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 0,
	'electricity_consumption', 40000,
	'air_consumption', 0,
	'DailySanityRecoverDome', 5000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "HangingGardens+-",
	'template_class', "HangingGardens",
	'pin_rollover_hint', T{527461368141, --[[ModItemBuildingTemplate HangingGardens+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{211918503484, --[[ModItemBuildingTemplate HangingGardens+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 40000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'construction_site_applies_height_surfaces', true,
	'achievement', "FirstDomeSpire",
	'maintenance_resource_type', "Concrete",
	'maintenance_resource_amount', 4000,
	'display_name', T{845126693591, --[[ModItemBuildingTemplate HangingGardens+- display_name]] "Hängende Gärten"},
	'display_name_pl', T{961819901954, --[[ModItemBuildingTemplate HangingGardens+- display_name_pl]] "Hängende Gärten"},
	'description', T{923919300439, --[[ModItemBuildingTemplate HangingGardens+- description]] "Eine wunderschöne Parkanlage. Erhöht den Komfort aller Wohngebäude innerhalb der Kuppel."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/hanging_gardens.tga",
	'build_pos', 2,
	'entity', "HangingGardens",
	'dome_comfort', 30000,
	'encyclopedia_image', "UI/Encyclopedia/HangingGardens.tga",
	'label1', "InsideBuildings",
	'palettes', "Outside_10",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(0, 0),
	'water_consumption', 2000,
	'air_consumption', 0,
	'service_comfort', 100000,
	'comfort_increase', 15000,
	'interest1', "interestRelaxation",
	'interest2', "interestExercise",
	'interest3', "interestPlaying",
	'max_visitors', 20,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Infirmary+",
	'template_class', "Infirmary",
	'pin_rollover_hint', T{759547985077, --[[ModItemBuildingTemplate Infirmary+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{653240742825, --[[ModItemBuildingTemplate Infirmary+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 15000,
	'build_points', 3000,
	'dome_required', true,
	'upgrade1_id', "Infirmary_RejuvenationTreatment",
	'upgrade1_display_name', T{173437280647, --[[ModItemBuildingTemplate Infirmary+ upgrade1_display_name]] "Verjüngungskur"},
	'upgrade1_description', T{778448734334, --[[ModItemBuildingTemplate Infirmary+ upgrade1_description]] "Erhöht den Service-Komfort. Kolonisten können ihn zur Entspannung nutzen."},
	'upgrade1_icon', "UI/Icons/Upgrades/rejuvenation_treatment_01.tga",
	'upgrade1_upgrade_cost_Polymers', 5000,
	'upgrade1_mod_prop_id_1', "service_comfort",
	'upgrade1_add_value_1', 30,
	'upgrade2_id', "Arcology_HomeCollective",
	'upgrade2_display_name', T{598813069264, --[[ModItemBuildingTemplate Infirmary+ upgrade2_display_name]] "No Workers"},
	'upgrade2_description', T{236064090944, --[[ModItemBuildingTemplate Infirmary+ upgrade2_description]] "No Workers"},
	'upgrade2_icon', "UI/Icons/Upgrades/home_collective_01.tga",
	'upgrade2_mod_prop_id_1', "automation",
	'upgrade2_add_value_1', 1,
	'upgrade2_mod_prop_id_2', "auto_performance",
	'upgrade2_add_value_2', 150,
	'upgrade2_mod_prop_id_3', "max_workers",
	'upgrade2_mul_value_3', -100,
	'use_demolished_state', false,
	'maintenance_resource_type', "Concrete",
	'display_name', T{585114672213, --[[ModItemBuildingTemplate Infirmary+ display_name]] "Krankenstation+"},
	'display_name_pl', T{437018932845, --[[ModItemBuildingTemplate Infirmary+ display_name_pl]] "Krankenhäuser"},
	'description', T{897495383096, --[[ModItemBuildingTemplate Infirmary+ description]] "Besucher regenerieren Gesundheit und Besonnenheit, solange sie nicht hungern, dehydriert sind, erfrieren oder ersticken. Kuppeln mit medizinischen Einrichtungen benötigen weniger Komfort für Geburten."},
	'build_category', "Dome Services",
	'display_icon', "UI/Icons/Buildings/infirmary.tga",
	'build_pos', 3,
	'entity', "Infirmary",
	'encyclopedia_image', "UI/Encyclopedia/Infirmary.tga",
	'label1', "InsideBuildings",
	'label2', "MedicalBuilding",
	'palettes', "Infirmary",
	'demolish_sinking', range(8, 18),
	'demolish_tilt_angle', range(600, 900),
	'demolish_debris', 80,
	'electricity_consumption', 2000,
	'health_change', 21000,
	'sanity_change', 20000,
	'interest1', "needMedical",
	'max_visitors', 15,
	'usable_by_children', true,
	'max_workers', 2,
	'specialist', "medic",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Large Solar Panel+",
	'template_class', "SolarPanel",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{644280622866, --[[ModItemBuildingTemplate Large Solar Panel+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{168569328929, --[[ModItemBuildingTemplate Large Solar Panel+ pin_rollover_hint_xbox]] "<image UI/Xbox/ButtonA.tga> View"},
	'construction_cost_Metals', 4000,
	'build_points', 1500,
	'show_range_class', "ArtificialSun",
	'maintenance_resource_type', "Metals",
	'display_name', T{438954398571, --[[ModItemBuildingTemplate Large Solar Panel+ display_name]] "Large Solar Panel+"},
	'display_name_pl', T{734634545218, --[[ModItemBuildingTemplate Large Solar Panel+ display_name_pl]] "Large Solar Panel"},
	'description', T{301380816673, --[[ModItemBuildingTemplate Large Solar Panel+ description]] "Generates 2500 Watts instead of 5."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/solar_aray.tga",
	'build_pos', 2,
	'entity', "SolarPanelBig",
	'encyclopedia_image', "UI/Encyclopedia/LargeSolarPanel.tga",
	'build_shortcut1', "J",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "SolarPanelBig",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 80,
	'electricity_production', 2500000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "MOXIE+",
	'template_class', "MOXIE",
	'pin_rollover_context', "air",
	'pin_rollover_hint', T{799040872058, --[[ModItemBuildingTemplate MOXIE+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{115299889524, --[[ModItemBuildingTemplate MOXIE+ pin_rollover_hint_xbox]] "<image UI/Xbox/ButtonA.tga> View"},
	'construction_cost_Metals', 5000,
	'build_points', 1500,
	'is_tall', true,
	'dome_forbidden', true,
	'upgrade1_id', "MOXIE_MagneticFiltering",
	'upgrade1_display_name', T{512343805497, --[[ModItemBuildingTemplate MOXIE+ upgrade1_display_name]] "Magnetic Filtering"},
	'upgrade1_description', T{512471648396, --[[ModItemBuildingTemplate MOXIE+ upgrade1_description]] "+<upgrade1_mul_value_1>% Production."},
	'upgrade1_icon', "UI/Icons/Upgrades/magnetic_filtering_01.tga",
	'upgrade1_upgrade_cost_Polymers', 5000,
	'upgrade1_mod_label_1', "MOXIE",
	'upgrade1_mod_prop_id_1', "air_production",
	'upgrade1_mul_value_1', 50,
	'maintenance_resource_type', "Metals",
	'maintenance_resource_amount', 2000,
	'display_name', T{405352753552, --[[ModItemBuildingTemplate MOXIE+ display_name]] "MOXIE+"},
	'display_name_pl', T{673314429915, --[[ModItemBuildingTemplate MOXIE+ display_name_pl]] "MOXIEs"},
	'description', T{393588986986, --[[ModItemBuildingTemplate MOXIE+ description]] "Produces 200 Oxygen instead of 2"},
	'build_category', "Life-Support",
	'display_icon', "UI/Icons/Buildings/moxie.tga",
	'entity', "Moxie",
	'encyclopedia_text', T{409503899571, --[[ModItemBuildingTemplate MOXIE+ encyclopedia_text]] "MOXIE instruments, which employ MOXIE (short for Mars Oxygen In situ resource utilization Experiment) technology, produce Oxygen from the rich amounts of carbon dioxide in the Martian atmosphere.\n\n<center><image UI/Common/rollover_line.tga 2000> <left>\n\nDeveloped in the 20th century but first tested on a rover mission to Mars in the early 20s of the 21st century, that once experimental technology now forms the backbone of life support in our first Colony on an alien world.\n\nThese instruments require nothing but power and regular maintenance and, of course, a connection to the lifeline of our Colony."},
	'encyclopedia_image', "UI/Encyclopedia/MOXIE.tga",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "Moxie",
	'demolish_sinking', range(1, 5),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 85,
	'electricity_consumption', 2000,
	'air_production', 200000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "MedicalCenter+-",
	'template_class', "MedicalCenter",
	'pin_rollover_hint', T{268432522241, --[[ModItemBuildingTemplate MedicalCenter+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{452398432443, --[[ModItemBuildingTemplate MedicalCenter+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 30000,
	'construction_cost_Metals', 30000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "MedicalCenter_HolographicScanner",
	'upgrade1_display_name', T{892350950899, --[[ModItemBuildingTemplate MedicalCenter+- upgrade1_display_name]] "Holografischer Scanner"},
	'upgrade1_description', T{531005020164, --[[ModItemBuildingTemplate MedicalCenter+- upgrade1_description]] "Erhöht die Geburtenrate innerhalb der Kuppel."},
	'upgrade1_icon', "UI/Icons/Upgrades/holographic_scanner_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_upgrade_cost_Electronics', 5000,
	'upgrade1_mod_target_1', "parent_dome",
	'upgrade1_mod_label_1', "Colonist",
	'upgrade1_mod_prop_id_1', "birth_comfort_modifier",
	'upgrade1_add_value_1', 30,
	'upgrade2_id', "MedicalCenter_RejuvenationTreatment",
	'upgrade2_display_name', T{400227878503, --[[ModItemBuildingTemplate MedicalCenter+- upgrade2_display_name]] "Verjüngungskur"},
	'upgrade2_description', T{578126552912, --[[ModItemBuildingTemplate MedicalCenter+- upgrade2_description]] "Erhöht den Service-Komfort. Kolonisten können ihn zur Entspannung nutzen."},
	'upgrade2_icon', "UI/Icons/Upgrades/rejuvenation_treatment_01.tga",
	'upgrade2_upgrade_cost_Polymers', 10000,
	'upgrade2_mod_label_1', "MedicalCenter",
	'upgrade2_mod_prop_id_1', "salvage_modifier",
	'upgrade2_mod_label_2', "MedicalCenter",
	'upgrade2_mod_prop_id_2', "service_comfort",
	'upgrade2_add_value_2', 15,
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 3000,
	'display_name', T{737948426215, --[[ModItemBuildingTemplate MedicalCenter+- display_name]] "Klinik"},
	'display_name_pl', T{307430674509, --[[ModItemBuildingTemplate MedicalCenter+- display_name_pl]] "Kliniken"},
	'description', T{832939770088, --[[ModItemBuildingTemplate MedicalCenter+- description]] "Besucher regenerieren Gesundheit und Besonnenheit, solange sie nicht hungern, dehydriert sind, erfrieren oder ersticken. Hat eine größere Kapazität und ist effektiver als die Krankenstation. Kuppeln mit medizinischen Einrichtungen benötigen weniger Komfort für Geburten."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/medical_center.tga",
	'build_pos', 7,
	'entity', "MedicalCenter",
	'encyclopedia_image', "UI/Encyclopedia/MedicalCenter.tga",
	'label1', "InsideBuildings",
	'label2', "MedicalBuilding",
	'palettes', "Outside_02",
	'demolish_sinking', range(10, 12),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 80,
	'electricity_consumption', 20000,
	'health_change', 50000,
	'sanity_change', 15000,
	'service_comfort', 70000,
	'comfort_increase', 15000,
	'interest1', "needMedical",
	'max_visitors', 10,
	'usable_by_children', true,
	'enabled_shift_3', false,
	'max_workers', 3,
	'specialist', "medic",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "MoholeMine",
	'template_class', "MoholeMine",
	'resource_produced1', "Metals",
	'max_storage1', 200000,
	'production_per_day1', 50000,
	'resource_produced2', "PreciousMetals",
	'max_storage2', 200000,
	'production_per_day2', 30000,
	'max_storage3', 0,
	'production_per_day3', 0,
	'stockpile_class3', "",
	'pin_rollover_hint', T{596329076230, --[[ModItemBuildingTemplate MoholeMine pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{974698434520, --[[ModItemBuildingTemplate MoholeMine pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 4000,
	'construction_cost_Metals', 1000,
	'construction_cost_MachineParts', 3000,
	'build_points', 120000,
	'instant_build', true,
	'dome_forbidden', true,
	'achievement', "BuiltMoholeMine",
	'use_demolished_state', false,
	'maintenance_resource_type', "Beton",
	'display_name', T{724650424369, --[[ModItemBuildingTemplate MoholeMine display_name]] "Mohole-Mine"},
	'display_name_pl', T{340290931048, --[[ModItemBuildingTemplate MoholeMine display_name_pl]] "Mohole-Minen"},
	'description', T{734476034024, --[[ModItemBuildingTemplate MoholeMine description]] "Die Mohole-Mine dringt tief unter die Kruste des Mars ein und erzeugt Metalle, Edelmetalle und Gesteinsabfälle. Dieser Vorgang beheizt außerdem die Umgebung."},
	'build_category', "Wonders",
	'display_icon', "UI/Icons/Buildings/mohole_mine.tga",
	'entity', "MoholeMine",
	'encyclopedia_image', "UI/Encyclopedia/MoholeMine.tga",
	'label1', "OutsideBuildings",
	'palettes', "MoholeMine",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(0, 0),
	'refund_on_salvage', false,
	'penalty_heat', 182,
	'penalty_pct', 51,
	'electricity_consumption', 4000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Moisture Vaporator+",
	'template_class', "MoistureVaporator",
	'pin_rollover_context', "water",
	'pin_rollover_hint', T{849340514600, --[[ModItemBuildingTemplate Moisture Vaporator+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{981981379387, --[[ModItemBuildingTemplate Moisture Vaporator+ pin_rollover_hint_xbox]] "<image UI/Xbox/ButtonA.tga> View"},
	'construction_cost_Metals', 2000,
	'construction_cost_Polymers', 5000,
	'build_points', 3000,
	'require_prefab', true,
	'is_tall', true,
	'dome_forbidden', true,
	'upgrade1_id', "MoistureVaporator_HygroscopicCoating",
	'upgrade1_display_name', T{559602021522, --[[ModItemBuildingTemplate Moisture Vaporator+ upgrade1_display_name]] "Hygroscopic Coating"},
	'upgrade1_description', T{107950339696, --[[ModItemBuildingTemplate Moisture Vaporator+ upgrade1_description]] "+<upgrade1_mul_value_1>% Production."},
	'upgrade1_icon', "UI/Icons/Upgrades/hygroscopic_coating_01.tga",
	'upgrade1_upgrade_cost_Polymers', 2000,
	'upgrade1_mod_label_1', "MoistureVaporator",
	'upgrade1_mod_prop_id_1', "water_production",
	'upgrade1_mul_value_1', 50,
	'upgrade2_id', "VectorPump",
	'upgrade2_display_name', T{263032969513, --[[ModItemBuildingTemplate Moisture Vaporator+ upgrade2_display_name]] "Vector Pump"},
	'upgrade2_description', T{280890852274, --[[ModItemBuildingTemplate Moisture Vaporator+ upgrade2_description]] "+<upgrade2_mul_value_1>% Production."},
	'upgrade2_icon', "UI/Icons/Upgrades/vector_pump_01.tga",
	'upgrade2_upgrade_cost_Polymers', 5000,
	'upgrade2_mod_label_1', "MoistureVaporator",
	'upgrade2_mod_prop_id_1', "water_production",
	'upgrade2_mul_value_1', 100,
	'maintenance_resource_type', "Metals",
	'maintenance_resource_amount', 2000,
	'display_name', T{849114599536, --[[ModItemBuildingTemplate Moisture Vaporator+ display_name]] "Moisture Vaporator+"},
	'display_name_pl', T{680279014178, --[[ModItemBuildingTemplate Moisture Vaporator+ display_name_pl]] "Moisture Vaporators"},
	'description', T{900940614853, --[[ModItemBuildingTemplate Moisture Vaporator+ description]] "Produce 100 Water"},
	'build_category', "Life-Support",
	'display_icon', "UI/Icons/Buildings/moisture_vaporator.tga",
	'build_pos', 4,
	'entity', "MoistureVaporator",
	'show_range_all', true,
	'encyclopedia_text', T{868707303628, --[[ModItemBuildingTemplate Moisture Vaporator+ encyclopedia_text]] "Moisture Vaporators provide a limitless, albeit slower and energy consuming, supply of water once water deposits are no longer a viable option. \n\n<center><image UI/Common/rollover_line.tga 2000> <left>\n\nMoisture Vaporators are based on WAVAR tech (Water-Vapor Adsorption Reactor), a process that extracts water directly from the Martian atmosphere by alternately blowing air over a zeolite adsorption bed and heating the bed to extract the absorbed water. While the water output is less than that of the Water Extractor, there is no end to the amount of water it can generate, and its mechanical simplicity means Water Vaporators can be deployed anywhere on the Martian surface."},
	'encyclopedia_image', "UI/Encyclopedia/MoistureVaporator.tga",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "MoistureVaporator",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 85,
	'water_production', 100000,
	'penalty_pct', 0,
	'electricity_consumption', 5000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "NetworkNode+-",
	'template_class', "NetworkNode",
	'pin_rollover_hint', T{409876018239, --[[ModItemBuildingTemplate NetworkNode+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{726237484824, --[[ModItemBuildingTemplate NetworkNode+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 50000,
	'construction_cost_Metals', 50000,
	'construction_cost_Electronics', 20000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "NetworkNode_Amplify",
	'upgrade1_display_name', T{283757225607, --[[ModItemBuildingTemplate NetworkNode+- upgrade1_display_name]] "Verstärken"},
	'upgrade1_description', T{161249123921, --[[ModItemBuildingTemplate NetworkNode+- upgrade1_description]] "+<upgrade1_mul_value_2> % Leistung; + Verbrauch."},
	'upgrade1_icon', "UI/Icons/Upgrades/amplify_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_mod_label_1', "NetworkNode",
	'upgrade1_mod_prop_id_1', "electricity_consumption",
	'upgrade1_add_value_1', 20000,
	'upgrade1_mod_label_2', "NetworkNode",
	'upgrade1_mod_prop_id_2', "performance",
	'upgrade1_mul_value_2', 25,
	'maintenance_resource_type', "Electronics",
	'maintenance_resource_amount', 3000,
	'display_name', T{193726892800, --[[ModItemBuildingTemplate NetworkNode+- display_name]] "Netzwerkknoten"},
	'display_name_pl', T{936232899030, --[[ModItemBuildingTemplate NetworkNode+- display_name_pl]] "Netzwerkknoten"},
	'description', T{996773017523, --[[ModItemBuildingTemplate NetworkNode+- description]] "Erhöht die gesamte Forschungsleistung innerhalb der Kuppel."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/network_node.tga",
	'build_pos', 5,
	'entity', "NetworkNode",
	'encyclopedia_image', "UI/Encyclopedia/NetworkNode.tga",
	'label1', "InsideBuildings",
	'palettes', "NetworkNode",
	'demolish_sinking', range(5, 10),
	'demolish_tilt_angle', range(60, 300),
	'electricity_consumption', 20000,
	'enabled_shift_2', false,
	'enabled_shift_3', false,
	'max_workers', 6,
	'specialist', "scientist",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Nursery+",
	'template_class', "Nursery",
	'pin_rollover_hint', T{941110200633, --[[ModItemBuildingTemplate Nursery+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{805099205109, --[[ModItemBuildingTemplate Nursery+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 10000,
	'build_points', 4000,
	'dome_required', true,
	'maintenance_resource_type', "Concrete",
	'display_name', T{505193702184, --[[ModItemBuildingTemplate Nursery+ display_name]] "Kindertagesstätte"},
	'display_name_pl', T{379424610747, --[[ModItemBuildingTemplate Nursery+ display_name_pl]] "Kindertagesstätten"},
	'description', T{645022012313, --[[ModItemBuildingTemplate Nursery+ description]] "Bietet Wohnraum für 20 Kinder."},
	'build_category', "Habitats",
	'display_icon', "UI/Icons/Buildings/nursery.tga",
	'build_pos', 5,
	'entity', "Nursery",
	'encyclopedia_image', "UI/Encyclopedia/Nursery.tga",
	'label1', "InsideBuildings",
	'palettes', "KinderGarden",
	'demolish_sinking', range(10, 15),
	'demolish_tilt_angle', range(300, 600),
	'electricity_consumption', 2000,
	'service_comfort', 60000,
	'comfort_increase', 5000,
	'capacity', 20,
	'children_only', true,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "OmegaTelescope",
	'template_class', "OmegaTelescope",
	'pin_rollover_hint', T{848531900182, --[[ModItemBuildingTemplate OmegaTelescope pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{917443357258, --[[ModItemBuildingTemplate OmegaTelescope pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 4000,
	'construction_cost_Metals', 3000,
	'construction_cost_Electronics', 3000,
	'build_points', 120000,
	'instant_build', true,
	'dome_forbidden', true,
	'achievement', "BuiltOmegaTelescope",
	'use_demolished_state', false,
	'maintenance_resource_type', "Beton",
	'display_name', T{801722853495, --[[ModItemBuildingTemplate OmegaTelescope display_name]] "Omega-Teleskop"},
	'display_name_pl', T{121524232836, --[[ModItemBuildingTemplate OmegaTelescope display_name_pl]] "Omega-Teleskope"},
	'description', T{842209444536, --[[ModItemBuildingTemplate OmegaTelescope description]] "Dieses Radioteleskop späht durch den Schleier des Unbekannten. Das führt zu bahnbrechenden Technologien und einer allgemein erhöhten Forschungsleistung."},
	'build_category', "Wonders",
	'display_icon', "UI/Icons/Buildings/omega_telescope.tga",
	'entity', "RadioDish",
	'encyclopedia_image', "UI/Encyclopedia/OmegaTelescope.tga",
	'label1', "OutsideBuildings",
	'palettes', "RadioDish",
	'demolish_sinking', range(5, 10),
	'demolish_tilt_angle', range(300, 720),
	'refund_on_salvage', false,
	'electricity_consumption', 8000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Oval Dome+",
	'template_class', "DomeOval",
	'pin_rollover_hint', T{482195571897, --[[ModItemBuildingTemplate Oval Dome+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{952227824431, --[[ModItemBuildingTemplate Oval Dome+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'pin_summary1', T{834947469253, --[[ModItemBuildingTemplate Oval Dome+ pin_summary1]] "<GetColonistCount><image UI/Icons/res_colonist.tga 800>"},
	'pin_on_start', true,
	'construction_entity', "DomeOvalConstruction",
	'build_points', 80000,
	'instant_build', true,
	'is_tall', true,
	'construction_site_applies_height_surfaces', true,
	'dome_forbidden', true,
	'achievement', "FirstDome",
	'use_demolished_state', false,
	'maintenance_resource_type', "Keine Wartung",
	'maintenance_resource_amount', 0,
	'display_name', T{316472540579, --[[ModItemBuildingTemplate Oval Dome+ display_name]] "Ovale Kuppel"},
	'display_name_pl', T{918954162645, --[[ModItemBuildingTemplate Oval Dome+ display_name_pl]] "Ovale Kuppeln"},
	'description', T{604553530112, --[[ModItemBuildingTemplate Oval Dome+ description]] "Ein längliches Kuppeldesign, das Platz für zwei Spitzen bietet."},
	'build_category', "Domes",
	'display_icon', "UI/Icons/Buildings/polymer_dome.tga",
	'build_pos', 4,
	'entity', "DomeOval",
	'dome_comfort', 100000,
	'encyclopedia_image', "UI/Encyclopedia/OvalDome.tga",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 0,
	'penalty_pct', 5,
	'defrost_time', 30000,
	'electricity_consumption', 0,
	'water_consumption', 0,
	'air_consumption', 0,
	'DailySanityRecoverDome', 85000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "OxygenTank+",
	'template_class', "OxygenTank",
	'pin_rollover_context', "air",
	'pin_rollover_hint', T{159184483385, --[[ModItemBuildingTemplate OxygenTank+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{305400585692, --[[ModItemBuildingTemplate OxygenTank+ pin_rollover_hint_xbox]] "<image UI/Xbox/ButtonA.tga> View"},
	'pin_progress_value', "current_storage",
	'pin_progress_max', "storage_capacity",
	'construction_cost_Metals', 3000,
	'build_points', 2000,
	'is_tall', true,
	'dome_forbidden', true,
	'maintenance_resource_type', "Metals",
	'display_name', T{328115904398, --[[ModItemBuildingTemplate OxygenTank+ display_name]] "Oxygen Tank+"},
	'display_name_pl', T{179621568365, --[[ModItemBuildingTemplate OxygenTank+ display_name_pl]] "Oxygen Tanks"},
	'description', T{785389752406, --[[ModItemBuildingTemplate OxygenTank+ description]] "Stores 10K more Oxygen"},
	'build_category', "Life-Support",
	'display_icon', "UI/Icons/Buildings/oxygen_tank.tga",
	'build_pos', 2,
	'entity', "AirTank",
	'encyclopedia_image', "UI/Encyclopedia/OxygenTank.tga",
	'entity2', "AirTankChrome",
	'entitydlc2', "dde",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'color_modifier', RGBA(18, 248, 27, 255),
	'palettes', "OxugenTank",
	'demolish_sinking', range(1, 5),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 80,
	'max_air_charge', 10000,
	'max_air_discharge', 10000,
	'air_capacity', 10000000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "ProjectMorpheus",
	'template_class', "ProjectMorpheus",
	'pin_rollover_hint', T{696331565737, --[[ModItemBuildingTemplate ProjectMorpheus pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{592238926846, --[[ModItemBuildingTemplate ProjectMorpheus pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 2000,
	'construction_cost_Metals', 4000,
	'construction_cost_Electronics', 3000,
	'build_points', 120000,
	'is_tall', true,
	'dome_forbidden', true,
	'achievement', "BuiltProjectMorpheus",
	'use_demolished_state', false,
	'maintenance_resource_type', "Beton",
	'display_name', T{318788154561, --[[ModItemBuildingTemplate ProjectMorpheus display_name]] "Morpheus-Projekt"},
	'display_name_pl', T{899412313254, --[[ModItemBuildingTemplate ProjectMorpheus display_name_pl]] "Morpheus-Projekte"},
	'description', T{559542309809, --[[ModItemBuildingTemplate ProjectMorpheus description]] "Dank des besseren Verständnisses des menschlichen Gehirns haben wir das Morpheus-Projekt gegründet. Das Gerät nutzt eine Kombination aus psychosomatischen Auslösern und suggestopädischer Methodik, um die Entwicklung neuer Stärken bei erwachsenen Kolonisten zu fördern."},
	'build_category', "Wonders",
	'display_icon', "UI/Icons/Buildings/project_morpheus.tga",
	'build_pos', 2,
	'entity', "ProjectMorpheus",
	'encyclopedia_image', "UI/Encyclopedia/ProjectMorpheus.tga",
	'label1', "OutsideBuildings",
	'palettes', "Morpheus",
	'demolish_sinking', range(5, 10),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 75,
	'demolish_return_resources', false,
	'refund_on_salvage', false,
	'electricity_consumption', 5000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Sanatorium+",
	'comment', "credits to ChoGGi",
	'template_class', "Sanatorium",
	'pin_rollover_hint', T{819387127899, --[[ModItemBuildingTemplate Sanatorium+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{890339645657, --[[ModItemBuildingTemplate Sanatorium+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 50000,
	'construction_cost_Metals', 20000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'dome_spot', "Spire",
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "Sanatorium_BehavioralMelding",
	'upgrade1_display_name', T{289535498204, --[[ModItemBuildingTemplate Sanatorium+ upgrade1_display_name]] "Verhaltensbezogene Verschmelzung"},
	'upgrade1_description', T{685433522919, --[[ModItemBuildingTemplate Sanatorium+ upgrade1_description]] "Ersetzt bei Besuchern Schwächen durch Stärken."},
	'upgrade1_icon', "UI/Icons/Upgrades/behavioral_melding_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_upgrade_cost_Electronics', 10000,
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 2000,
	'display_name', "Sanatorium+",
	'display_name_pl', T{230037413528, --[[ModItemBuildingTemplate Sanatorium+ display_name_pl]] "Sanatorien"},
	'description', "Treats Colonists for ALL flaws through advanced and (mostly humane) medical practices.",
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/sanatorium.tga",
	'build_pos', 7,
	'entity', "Sanatorium",
	'encyclopedia_image', "UI/Encyclopedia/Sanatorium.tga",
	'label1', "InsideBuildings",
	'palettes', "Sanatorium",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(300, 600),
	'electricity_consumption', 20000,
	'enabled_shift_1', false,
	'enabled_shift_3', false,
	'max_visitors', 12,
	'evaluation_points', 200,
	'trait1', "Gambler",
	'trait2', "Alcoholic",
	'trait3', "Glutton",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Sanatorium+-",
	'template_class', "Sanatorium",
	'pin_rollover_hint', T{872788521943, --[[ModItemBuildingTemplate Sanatorium+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{800426132236, --[[ModItemBuildingTemplate Sanatorium+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 50000,
	'construction_cost_Metals', 20000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "Sanatorium_BehavioralMelding",
	'upgrade1_display_name', T{925392305013, --[[ModItemBuildingTemplate Sanatorium+- upgrade1_display_name]] "Verhaltensbezogene Verschmelzung"},
	'upgrade1_description', T{598281106363, --[[ModItemBuildingTemplate Sanatorium+- upgrade1_description]] "Ersetzt bei Besuchern Schwächen durch Stärken."},
	'upgrade1_icon', "UI/Icons/Upgrades/behavioral_melding_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_upgrade_cost_Electronics', 10000,
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 2000,
	'display_name', T{783650045300, --[[ModItemBuildingTemplate Sanatorium+- display_name]] "Sanatorium"},
	'display_name_pl', T{970241074843, --[[ModItemBuildingTemplate Sanatorium+- display_name_pl]] "Sanatorien"},
	'description', T{317032285733, --[[ModItemBuildingTemplate Sanatorium+- description]] "Behandelt Kolonisten, um Schwächen mit fortschrittlichen und meist menschlichen Methoden zu heilen."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/sanatorium.tga",
	'build_pos', 7,
	'entity', "Sanatorium",
	'encyclopedia_image', "UI/Encyclopedia/Sanatorium.tga",
	'label1', "InsideBuildings",
	'palettes', "Sanatorium",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(300, 600),
	'electricity_consumption', 20000,
	'enabled_shift_1', false,
	'enabled_shift_3', false,
	'max_visitors', 4,
	'evaluation_points', 200,
	'trait1', "Gambler",
	'trait2', "Alcoholic",
	'trait3', "Glutton",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Solar Panel+",
	'template_class', "SolarPanel",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{165837649100, --[[ModItemBuildingTemplate Solar Panel+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{660498202894, --[[ModItemBuildingTemplate Solar Panel+ pin_rollover_hint_xbox]] "<image UI/Xbox/ButtonA.tga> View"},
	'construction_cost_Metals', 1000,
	'build_points', 500,
	'show_range_class', "ArtificialSun",
	'maintenance_resource_type', "Metals",
	'maintenance_resource_amount', 500,
	'display_name', T{461678390793, --[[ModItemBuildingTemplate Solar Panel+ display_name]] "Solar Panel+"},
	'display_name_pl', T{712257787798, --[[ModItemBuildingTemplate Solar Panel+ display_name_pl]] "Solar Panels"},
	'description', T{866117814451, --[[ModItemBuildingTemplate Solar Panel+ description]] "Generates 1000 Watts instead of 2."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/solar_panel.tga",
	'entity', "SolarPanel",
	'encyclopedia_image', "UI/Encyclopedia/SolarPanel.tga",
	'build_shortcut1', "N",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "Outside_01",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(300, 600),
	'electricity_production', 1000000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StirlingGenerator",
	'template_class', "StirlingGenerator",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{782536574262, --[[ModItemBuildingTemplate StirlingGenerator pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{811717348450, --[[ModItemBuildingTemplate StirlingGenerator pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Polymers', 12000,
	'construction_cost_Electronics', 6000,
	'build_points', 1000,
	'instant_build', true,
	'upgrade1_id', "StirlingGenerator_PlutoniumCore",
	'upgrade1_display_name', T{618451641882, --[[ModItemBuildingTemplate StirlingGenerator upgrade1_display_name]] "Plutoniumkern"},
	'upgrade1_description', T{907090098552, --[[ModItemBuildingTemplate StirlingGenerator upgrade1_description]] "+<upgrade1_mul_value_1> % zusätzliche Stromerzeugung, wenn geöffnet."},
	'upgrade1_icon', "UI/Icons/Upgrades/plutonium_core_01.tga",
	'upgrade1_upgrade_cost_Polymers', 4000,
	'upgrade1_mod_label_1', "StirlingGenerator",
	'upgrade1_mod_prop_id_1', "production_factor_interacted",
	'upgrade1_mul_value_1', 50,
	'use_demolished_state', false,
	'maintenance_resource_type', "Polymers",
	'display_name', T{373542696235, --[[ModItemBuildingTemplate StirlingGenerator display_name]] "Stirling-Generator"},
	'display_name_pl', T{657594807955, --[[ModItemBuildingTemplate StirlingGenerator display_name_pl]] "Stirling-Generatoren"},
	'description', T{118574658264, --[[ModItemBuildingTemplate StirlingGenerator description]] "Generates 1000 Watts instead of 10, 2000 if opened."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/stirling_generator.tga",
	'build_pos', 4,
	'entity', "StirlingGenerator",
	'encyclopedia_image', "UI/Encyclopedia/StirlingGenerator.tga",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "StirlingGenerator",
	'demolish_sinking', range(5, 10),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 80,
	'demolish_return_resources', false,
	'refund_on_salvage', false,
	'electricity_production', 1000000,
	'production_factor_interacted', 200,
	'daily_dust_accumulation', 2000000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageConcrete+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{193488689978, --[[ModItemBuildingTemplate StorageConcrete+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{232845423578, --[[ModItemBuildingTemplate StorageConcrete+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{288422932487, --[[ModItemBuildingTemplate StorageConcrete+ display_name]] "Betonlager+"},
	'display_name_pl', T{529638967961, --[[ModItemBuildingTemplate StorageConcrete+ display_name_pl]] "Betonlager"},
	'description', T{136460256835, --[[ModItemBuildingTemplate StorageConcrete+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/concrete_storage.tga",
	'build_pos', 3,
	'entity', "StorageDepotSmall_03",
	'encyclopedia_image', "UI/Encyclopedia/ConcreteDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Concrete",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageElectronics+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{487243595651, --[[ModItemBuildingTemplate StorageElectronics+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{676339909117, --[[ModItemBuildingTemplate StorageElectronics+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{806898071058, --[[ModItemBuildingTemplate StorageElectronics+ display_name]] "Elektroniklager+"},
	'display_name_pl', T{707489916327, --[[ModItemBuildingTemplate StorageElectronics+ display_name_pl]] "Elektroniklager"},
	'description', T{466361454838, --[[ModItemBuildingTemplate StorageElectronics+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/electronics_storage.tga",
	'build_pos', 7,
	'entity', "StorageDepotSmall_08",
	'encyclopedia_image', "UI/Encyclopedia/ElectronicsDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Electronics",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageFood+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{558630286705, --[[ModItemBuildingTemplate StorageFood+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{646411655203, --[[ModItemBuildingTemplate StorageFood+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{425221173774, --[[ModItemBuildingTemplate StorageFood+ display_name]] "Nahrungsspeicher+"},
	'display_name_pl', T{951290951857, --[[ModItemBuildingTemplate StorageFood+ display_name_pl]] "Nahrungsspeicher"},
	'description', T{773280929111, --[[ModItemBuildingTemplate StorageFood+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/food_storage.tga",
	'build_pos', 4,
	'entity', "StorageDepotSmall_04",
	'encyclopedia_image', "UI/Encyclopedia/FoodDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Food",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageFuel+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{212779770237, --[[ModItemBuildingTemplate StorageFuel+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{883497115255, --[[ModItemBuildingTemplate StorageFuel+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{322796533594, --[[ModItemBuildingTemplate StorageFuel+ display_name]] "Treibstofflager+"},
	'display_name_pl', T{471871228362, --[[ModItemBuildingTemplate StorageFuel+ display_name_pl]] "Treibstofflager"},
	'description', T{643228794311, --[[ModItemBuildingTemplate StorageFuel+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/fuel_storage.tga",
	'build_pos', 9,
	'entity', "StorageDepotSmall_06",
	'encyclopedia_image', "UI/Encyclopedia/FuelDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Fuel",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageMachineParts+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{748855749431, --[[ModItemBuildingTemplate StorageMachineParts+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{492857578930, --[[ModItemBuildingTemplate StorageMachineParts+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{520199501300, --[[ModItemBuildingTemplate StorageMachineParts+ display_name]] "Maschinenteilelager+"},
	'display_name_pl', T{365982537057, --[[ModItemBuildingTemplate StorageMachineParts+ display_name_pl]] "Maschinenteilelager"},
	'description', T{874659034462, --[[ModItemBuildingTemplate StorageMachineParts+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/machine_parts_storage.tga",
	'build_pos', 8,
	'entity', "StorageDepotSmall_05",
	'encyclopedia_image', "UI/Encyclopedia/MachinePartsDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"MachineParts",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageMetals+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{977829429768, --[[ModItemBuildingTemplate StorageMetals+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{619336344963, --[[ModItemBuildingTemplate StorageMetals+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{263400290503, --[[ModItemBuildingTemplate StorageMetals+ display_name]] "Metalllager+"},
	'display_name_pl', T{298664278182, --[[ModItemBuildingTemplate StorageMetals+ display_name_pl]] "Metalllager"},
	'description', T{651028626323, --[[ModItemBuildingTemplate StorageMetals+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/metal_storage.tga",
	'build_pos', 2,
	'entity', "StorageDepotSmall_02",
	'encyclopedia_image', "UI/Encyclopedia/MetalsDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Metals",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StoragePolymers+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{562098738108, --[[ModItemBuildingTemplate StoragePolymers+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{425829957876, --[[ModItemBuildingTemplate StoragePolymers+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{888372507367, --[[ModItemBuildingTemplate StoragePolymers+ display_name]] "Polymer-Lager+"},
	'display_name_pl', T{475903711339, --[[ModItemBuildingTemplate StoragePolymers+ display_name_pl]] "Polymer-Lager"},
	'description', T{538257468584, --[[ModItemBuildingTemplate StoragePolymers+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/polymers_storage.tga",
	'build_pos', 6,
	'entity', "StorageDepotSmall_01",
	'encyclopedia_image', "UI/Encyclopedia/PolymersDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"Polymers",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "StorageRareMetals+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{426157998565, --[[ModItemBuildingTemplate StorageRareMetals+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{345853565178, --[[ModItemBuildingTemplate StorageRareMetals+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'build_points', 0,
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{784253460680, --[[ModItemBuildingTemplate StorageRareMetals+ display_name]] "Edelmetalllager+"},
	'display_name_pl', T{612386400339, --[[ModItemBuildingTemplate StorageRareMetals+ display_name_pl]] "Edelmetalllager"},
	'description', T{291422709738, --[[ModItemBuildingTemplate StorageRareMetals+ description]] "Bietet Platz zur Lagerung von . Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/rare_metals_storage.tga",
	'build_pos', 5,
	'entity', "StorageDepotSmall_07",
	'encyclopedia_image', "UI/Encyclopedia/RareMetalsDepot.tga",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 300000,
	'max_x', 12,
	'storable_resources', {
		"PreciousMetals",
	},
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "TheExcavator",
	'template_class', "TheExcavator",
	'pin_rollover_hint', T{723109519910, --[[ModItemBuildingTemplate TheExcavator pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{474102836871, --[[ModItemBuildingTemplate TheExcavator pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 1000,
	'construction_cost_Metals', 3000,
	'construction_cost_MachineParts', 2000,
	'build_points', 120000,
	'instant_build', true,
	'dome_forbidden', true,
	'force_extend_bb_during_placement_checks', 12000,
	'achievement', "BuiltExcavator",
	'use_demolished_state', false,
	'maintenance_resource_type', "Beton",
	'display_name', T{549057000915, --[[ModItemBuildingTemplate TheExcavator display_name]] "Der Ausgräber"},
	'display_name_pl', T{652313839122, --[[ModItemBuildingTemplate TheExcavator display_name_pl]] "Die Ausgräber"},
	'description', T{294454743898, --[[ModItemBuildingTemplate TheExcavator description]] "Durch den Einsatz fortschrittlicher Förderungstechnologien kann aus der Marserde direkt Beton hergestellt werden, sodass kein Vorkommen erforderlich ist."},
	'build_category', "Wonders",
	'display_icon', "UI/Icons/Buildings/the_excavator.tga",
	'build_pos', 2,
	'entity', "Excavator",
	'encyclopedia_image', "UI/Encyclopedia/TheExcavator.tga",
	'label1', "OutsideBuildings",
	'palettes', "MoholeMine",
	'demolish_sinking', range(1, 5),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 30,
	'demolish_return_resources', false,
	'electricity_consumption', 3000,
	'resource_produced1', "Concrete",
	'max_storage1', 200000,
	'production_per_day1', 3000,
	'resource_produced2', "PreciousMetals",
	'max_storage2', 200000,
	'production_per_day2', 15000,
	'max_storage3', 0,
	'production_per_day3', 0,
	'stockpile_class3', "",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "UniversalStorageDepot+",
	'template_class', "UniversalStorageDepot",
	'pin_rollover_hint', T{261319088815, --[[ModItemBuildingTemplate UniversalStorageDepot+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{503802102551, --[[ModItemBuildingTemplate UniversalStorageDepot+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'instant_build', true,
	'dome_forbidden', true,
	'display_name', T{370787035871, --[[ModItemBuildingTemplate UniversalStorageDepot+ display_name]] "Universallager+"},
	'display_name_pl', T{657135291698, --[[ModItemBuildingTemplate UniversalStorageDepot+ display_name_pl]] "Universallager"},
	'description', T{768020556396, --[[ModItemBuildingTemplate UniversalStorageDepot+ description]] "Bietet Platz zur Lagerung von  Einheiten jeder transportierbaren Ressource. Überschüssige Ressourcen werden automatisch zu anderen Depots in Reichweite der Drohne gebracht."},
	'build_category', "Storages",
	'display_icon', "UI/Icons/Buildings/universal_storage.tga",
	'entity', "StorageDepot",
	'encyclopedia_image', "UI/Encyclopedia/UniversalDepot.tga",
	'build_shortcut1', "U",
	'on_off_button', false,
	'prio_button', false,
	'demolish_sinking', range(15, 30),
	'demolish_tilt_angle', range(300, 600),
	'max_storage_per_resource', 100000,
	'switch_fill_order', false,
	'fill_group_idx', 9,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Water Tower+",
	'template_class', "WaterTank",
	'pin_rollover_context', "water",
	'pin_rollover_hint', T{257736286086, --[[ModItemBuildingTemplate Water Tower+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{494310120332, --[[ModItemBuildingTemplate Water Tower+ pin_rollover_hint_xbox]] "<image UI/Xbox/ButtonA.tga> View"},
	'pin_progress_value', "current_storage",
	'pin_progress_max', "storage_capacity",
	'construction_cost_Metals', 3000,
	'build_points', 2000,
	'is_tall', true,
	'dome_forbidden', true,
	'maintenance_resource_type', "Metals",
	'display_name', T{896413215580, --[[ModItemBuildingTemplate Water Tower+ display_name]] "Water Tower+"},
	'display_name_pl', T{494616910433, --[[ModItemBuildingTemplate Water Tower+ display_name_pl]] "Water Towers"},
	'description', T{680712247521, --[[ModItemBuildingTemplate Water Tower+ description]] "Stores 10K of Water."},
	'build_category', "Life-Support",
	'display_icon', "UI/Icons/Buildings/water_tank.tga",
	'build_pos', 5,
	'entity', "WaterTank",
	'encyclopedia_image', "UI/Encyclopedia/WaterTank.tga",
	'entity2', "WaterTankChrome",
	'entitydlc2', "dde",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "WaterTank",
	'demolish_sinking', range(1, 5),
	'demolish_tilt_angle', range(60, 300),
	'demolish_debris', 76,
	'max_water_charge', 10000,
	'max_water_discharge', 10000,
	'water_capacity', 10000000,
	'penalty_pct', 0,
	'freeze_time', 1000,
	'defrost_time', 1000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "WaterReclamationSystem+-",
	'template_class', "WaterReclamationSpire",
	'pin_rollover_hint', T{178881056494, --[[ModItemBuildingTemplate WaterReclamationSystem+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{101827041927, --[[ModItemBuildingTemplate WaterReclamationSystem+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 50000,
	'construction_cost_Polymers', 10000,
	'construction_cost_MachineParts', 5000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'maintenance_resource_type', "MachineParts",
	'maintenance_resource_amount', 3000,
	'display_name', T{873158704560, --[[ModItemBuildingTemplate WaterReclamationSystem+- display_name]] "WRS"},
	'display_name_pl', T{738604447158, --[[ModItemBuildingTemplate WaterReclamationSystem+- display_name_pl]] "WRS"},
	'description', T{315119008662, --[[ModItemBuildingTemplate WaterReclamationSystem+- description]] "Verwertet 70 % des verbrauchten Wassers innerhalb der Kuppel wieder."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/water_reclamation.tga",
	'build_pos', 3,
	'entity', "WaterReclamation",
	'encyclopedia_image', "UI/Encyclopedia/WaterReclamationSystem.tga",
	'label1', "InsideBuildings",
	'palettes', "WaterReclamation",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(0, 0),
	'max_workers', 2,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Wind Turbine+",
	'template_class', "WindTurbine",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{862483739647, --[[ModItemBuildingTemplate Wind Turbine+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{705053535530, --[[ModItemBuildingTemplate Wind Turbine+ pin_rollover_hint_xbox]] "<image UI/Xbox/ButtonA.tga> View"},
	'construction_cost_Concrete', 4000,
	'construction_cost_MachineParts', 1000,
	'build_points', 1500,
	'is_tall', true,
	'dome_forbidden', true,
	'upgrade1_id', "WindTurbine_PolymerBlades",
	'upgrade1_display_name', T{784653324232, --[[ModItemBuildingTemplate Wind Turbine+ upgrade1_display_name]] "Polymer Blades"},
	'upgrade1_description', T{652550931215, --[[ModItemBuildingTemplate Wind Turbine+ upgrade1_description]] "+<upgrade1_mul_value_1>% Production."},
	'upgrade1_icon', "UI/Icons/Upgrades/polymer_blades_01.tga",
	'upgrade1_upgrade_cost_Polymers', 2000,
	'upgrade1_mod_label_1', "WindTurbine",
	'upgrade1_mod_prop_id_1', "electricity_production",
	'upgrade1_mul_value_1', 33,
	'maintenance_resource_type', "MachineParts",
	'maintenance_resource_amount', 500,
	'display_name', T{152031694155, --[[ModItemBuildingTemplate Wind Turbine+ display_name]] "Wind Turbine+"},
	'display_name_pl', T{957965796272, --[[ModItemBuildingTemplate Wind Turbine+ display_name_pl]] "Wind Turbines"},
	'description', T{832345013487, --[[ModItemBuildingTemplate Wind Turbine+ description]] "Generates 1000 Watts instead of 5, plus more depending on elevations."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/wind_turbine.tga",
	'build_pos', 3,
	'entity', "WindTurbine",
	'encyclopedia_text', T{554317920150, --[[ModItemBuildingTemplate Wind Turbine+ encyclopedia_text]] "Wind turbines generate electrical power from the Martian winds. The amount generated depends on how powerful the winds they are exposed to are, so proper positioning is essential as higher ground tends to be windier.\n\n<center><image UI/Common/rollover_line.tga 2000> <left>\n\nWhile wind speeds on Mars are generally mild, they can reach incredible speeds during dust storms. Still, the thin Martian atmosphere dictates that the average wind turbine would need winds around six times more powerful than those on Earth to create the same amount of thrust.\n \nThis technological challenge to take advantage of what little wind there is on Mars was solved by opting for vertical axis wind turbines, which are capable of catching the wind from all directions, instead of simply horizontal.  The materials used are light enough to self-start on much weaker forces than those most commonly used on Earth."},
	'encyclopedia_image', "UI/Encyclopedia/WindTurbine.tga",
	'entity2', "WindTurbineChrome",
	'entitydlc2', "dde",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "WindTurbine",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 85,
	'electricity_production', 1000000,
	'bonus_per_kilometer_elevation', 1000,
	'min_production_to_work', 0,
	'dust_storm_bonus_percent', 100,
	'great_dust_storm_bonus_percent', 200,
}),
PlaceObj('ModItemCode', {
	'comment', "Enables trailblazer Skin   (credits to ChoGGi)",
	'FileName', "Code/Script.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script2",
	'comment', "Sanatoriums cure all negative traits, and Sanatorium+ treats 12 instead of 4 people at a time",
	'FileName', "Code/Script2.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script3",
	'comment', "Enables Info Panel Cheats  ;; credits to ChoGGi",
	'FileName', "Code/Script3.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script4",
	'FileName', "Code/Script4.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Script5",
	'FileName', "Code/Script5.lua",
}),
PlaceObj('ModItemGameValue', {
	'name', "rs c",
	'category', "Research",
	'id', "SponsorResearch",
	'percent', 100000,
	'amount', 100000,
}),
PlaceObj('ModItemMissionSponsor', {
	'name', "Hitchhiker´s Way",
	'comment', "42",
	'display_name', T{217914769787, --[[ModItemMissionSponsor Hitchhiker´s Way display_name]] "Hitchhiker´s Way"},
	'challenge_mod', 400,
	'funding', 900000,
	'funding_per_tech', 200000,
	'funding_per_breakthrough', 100000,
	'applicants_per_breakthrough', 60,
	'cargo', 100000000,
	'initial_rockets', 10,
	'rocket_price', 1000000,
	'applicants_price', 1000000,
	'initial_techs_unlocked', 40,
	'trait', "Partylöwe",
	'anomaly_bonus_breakthrough', range(4, 4),
	'anomaly_bonus_event', range(4, 4),
	'anomaly_bonus_free_tech', range(4, 4),
	'effect', T{333082392538, --[[ModItemMissionSponsor Hitchhiker´s Way effect]] "Difficulty: <color 250 236 208>Hard</color><newline><newline>Funding: $<funding> M<newline>Research per Sol: <newline>Rare Metals price: $<ExportPricePreciousMetals> M<newline>Starting Applicants: <ApplicantsPoolStartingSize><newline><newline>- Drone Hubs start with additional Drones<newline>- 50% cheaper advanced resources"},
	'default_skin', "Star",
	'game_apply', function (self, city)
const.BreakThroughTechsPerGame = 45
const.OmegaTelescopeBreakthroughsCount = 25
const.CommandCenterMaxRadius = 100
const.RCRoverMaxRadius = 40
end,
	'goal', "MG_Colonists",
	'goal_target', 250,
	'sponsor_nation_name1', "German",
	'sponsor_nation_percent1', 20,
	'RCRover', 1,
	'ExplorerRover', 1,
	'Drone', 72,
	'Concrete', 20000,
	'Metals', 20000,
	'Food', 20000,
	'Polymers', 20000,
	'MachineParts', 20000,
	'Electronics', 20000,
	'DroneHub', 50,
	'MoistureVaporator', 50,
	'FuelFactory', 50,
	'StirlingGenerator', 50,
	'MachinePartsFactory', 50,
	'ElectronicsFactory', 50,
	'PolymerPlant', 50,
	'OrbitalProbe', 100,
}),
}
