return {
PlaceObj('ModItemBuildingTemplate', {
	'name', "DroneFactory",
	'template_class', "DroneFactory",
	'pin_rollover_hint', T{614401687188, --[[ModItemBuildingTemplate DroneFactory pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{983282025116, --[[ModItemBuildingTemplate DroneFactory pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Metals', 2000,
	'construction_cost_Electronics', 1000,
	'build_points', 7000,
	'is_tall', true,
	'dome_forbidden', true,
	'upgrade1_id', "Arcology_HomeCollective",
	'upgrade1_display_name', T{838047373238, --[[ModItemBuildingTemplate DroneFactory upgrade1_display_name]] "No Workers needed"},
	'upgrade1_description', T{907957290725, --[[ModItemBuildingTemplate DroneFactory upgrade1_description]] "No Workers needed"},
	'upgrade1_icon', "UI/Icons/Upgrades/home_collective_01.tga",
	'upgrade1_mod_prop_id_1', "automation",
	'upgrade1_add_value_1', 1,
	'upgrade1_mod_prop_id_2', "auto_performance",
	'upgrade1_add_value_2', 150,
	'upgrade1_mod_prop_id_3', "max_workers",
	'upgrade1_mul_value_3', -100,
	'maintenance_resource_type', "Electronics",
	'display_name', T{170955752832, --[[ModItemBuildingTemplate DroneFactory display_name]] "Drohnenfabrik"},
	'display_name_pl', T{280577920116, --[[ModItemBuildingTemplate DroneFactory display_name_pl]] "Drohnenfabriken"},
	'description', T{891019933037, --[[ModItemBuildingTemplate DroneFactory description]] "Stellt Drohnen-Fertigbauten her, dank denen in Drohnen-Hubs Drohnen – die gehorsamen Arbeitskräfte der Kolonie – bestellt werden können. Wahrscheinlich keine Gefahr für die Menschheit."},
	'build_category', "Production",
	'display_icon', "UI/Icons/Buildings/workshop.tga",
	'build_pos', 4,
	'entity', "Workshop",
	'encyclopedia_image', "UI/Encyclopedia/DroneAssembler.tga",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "Outside_02",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(600, 1200),
	'demolish_debris', 85,
	'electricity_consumption', 10000,
	'max_workers', 3,
	'specialist', "engineer",
}),
}
