return {
  PlaceObj("ModItemCode",{"FileName","Script.lua"})
,

PlaceObj("ModItemBuildingTemplate", {
  "name",  "Sanatorium+",
  "template_class",  "Sanatorium",
  "construction_cost_Concrete",  50000,
  "construction_cost_Metals",  20000,
  "construction_cost_Polymers",  10000,
  "build_points",  30000,
  "require_prefab",  true,
  "is_tall",  true,
  --"dome_required",  true,
  "dome_spot",  "Spire",
  "achievement",  "FirstDomeSpire",
  "upgrade1_id",  "Sanatorium_BehavioralMelding",
  "upgrade1_display_name",T({5243,"Behavioral Melding"}),
  "upgrade1_description",T({5244,"Replaces flaws with Perks for visitors."}),
  "upgrade1_icon",  "UI/Icons/Upgrades/behavioral_melding_01.tga",
  "upgrade1_upgrade_cost_Polymers",  10000,
  "upgrade1_upgrade_cost_Electronics",  10000,
  "maintenance_resource_type",  "Polymers",
  "maintenance_resource_amount",  2000,
  "display_name",  "Sanatorium+",
  "display_name_pl",T({5245,"Sanatoriums"}),
  "description","Treats Colonists for ALL flaws through advanced and (mostly humane) medical practices.",
  "build_category",  "Dome Spires",
  "display_icon",  "UI/Icons/Buildings/sanatorium.tga",
  "build_pos",  7,
  "entity",  "Sanatorium",
  "encyclopedia_image",  "UI/Encyclopedia/Sanatorium.tga",
  "label1",  "InsideBuildings",
  "palettes",  "Sanatorium",
  "demolish_sinking",  range(5, 15),
  "electricity_consumption",  20000,
  "enabled_shift_1",  false,
  "enabled_shift_3",  false,
  --"max_visitors",  4,
  "max_visitors",  12,
  "evaluation_points",  200,
  "trait1",  "Gambler",
  "trait2",  "Alcoholic",
  "trait3",  "Glutton",
}),

}
