return {

PlaceObj('ModItemCode', {
	'name', "Script",
	'FileName', "Script.lua"
}),

PlaceObj('ModItemBuildingTemplate', {
	'name', "ArcologyX",
	'template_class', "Arcology",
	'construction_cost_Concrete', 80000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'is_tall', true,
	'dome_required', true,
	'dome_spot', "Spire",
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "Arcology_HomeCollective",
	'upgrade1_display_name', T{5005,"Home Collective"},
	'upgrade1_description', T{5006, "+<upgrade1_add_value_1> Service Comfort"},
	'upgrade1_icon', "UI/Icons/Upgrades/home_collective_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_mod_label_1', "Arcology",
	'upgrade1_mod_prop_id_1', "service_comfort",
	'upgrade1_add_value_1', 60,
	'upgrade1_mod_label_2', "Dome Comfort",
	'upgrade1_mod_prop_id_2', "dome_comfort",
	'upgrade1_add_value_2', 60,
	'upgrade1_mod_label_3', "Unit",
	'upgrade1_mod_prop_id_3', "MaxColonistsPerRocket",
	'upgrade1_add_value_3', 50,
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 4000,
	'display_name', "ArcologyX",
	'display_name_pl',"ArcologyX",
  "description",  T({5009,"Provides living space for numerous Colonists, granting high Comfort."}),
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/arcology.tga",
	'entity', "Arcology",
	'encyclopedia_image', "UI/Encyclopedia/Arcology.tga",
	'label1', "InsideBuildings",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(0, 0),
	'demolish_debris', 90,
	'spire_frame_entity', "ArcologyFrame",
	'electricity_consumption', 20000,

	--'service_comfort', 35000,
  --why'd BoehserOnkel lower this?
	'service_comfort', 60000,
	'comfort_increase', 20000,

	'health_change', 20000,
	'sanity_change', 20000,
	'rest_duration', 30000,
	'sanity_increase', 20000,

	'capacity', 256,
}),
}
