return {
PlaceObj('ModItemBuildingTemplate', {
	'name', "Arcology+",
	'template_class', "Arcology",
	'pin_rollover_hint', T{300310177360, --[[ModItemBuildingTemplate Arcology+ pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{841390443088, --[[ModItemBuildingTemplate Arcology+ pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 80000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'is_tall', true,
	'dome_required', true,
	'dome_spot', "Spire",
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "Arcology_HomeCollective",
	'upgrade1_display_name', T{516736833841, --[[ModItemBuildingTemplate Arcology+ upgrade1_display_name]] "Heimatgemeinschaft"},
	'upgrade1_description', T{689467866170, --[[ModItemBuildingTemplate Arcology+ upgrade1_description]] "+<upgrade1_add_value_1> Service-Komfort"},
	'upgrade1_icon', "UI/Icons/Upgrades/home_collective_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_mod_label_1', "Arcology",
	'upgrade1_mod_prop_id_1', "service_comfort",
	'upgrade1_add_value_1', 60,
	'upgrade1_mod_label_2', "Kuppelkomfort+",
	'upgrade1_mod_prop_id_2', "dome_comfort",
	'upgrade1_add_value_2', 60,
	'upgrade1_mod_label_3', "Kol+",
	'upgrade1_mod_prop_id_3', "MaxColonistsPerRocket",
	'upgrade1_add_value_3', 50,
	'maintenance_resource_type', "Keine Wartung",
	'maintenance_resource_amount', 4000,
	'display_name', T{829919567952, --[[ModItemBuildingTemplate Arcology+ display_name]] "Arkologie+"},
	'display_name_pl', T{896098660173, --[[ModItemBuildingTemplate Arcology+ display_name_pl]] "Arkologie"},
	'description', T{795854905433, --[[ModItemBuildingTemplate Arcology+ description]] "Bietet Wohnraum für zahlreiche Kolonisten und gewährt viel Komfort."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/arcology.tga",
	'entity', "Arcology",
	'encyclopedia_image', "UI/Encyclopedia/Arcology.tga",
	'label1', "InsideBuildings",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(0, 0),
	'demolish_debris', 90,
	'spire_frame_entity', "ArcologyFrame",
	'electricity_consumption', 20000,
	'health_change', 20000,
	'sanity_change', 20000,
	'service_comfort', 35000,
	'comfort_increase', 20000,
	'capacity', 120,
	'rest_duration', 30000,
	'sanity_increase', 20000,
}),
}
