DefineClass("ModOptions_ChoGGi_PortableMiner", {
	__parents = {
		"ModOptionsObject",
	},
	properties = {
		{
			default = 1,
			editor = "number",
			id = "mine_amount",
			max = 500,
			min = 1,
			name = "Amount per mine anim",
			desc = "How much is mined each time.",
		},
		{
			default = 90,
			editor = "number",
			id = "max_res_amount_man",
			max = 1000,
			min = 1,
			name = "Amount stored in stockpile manual",
			desc = "XXXXXXXXXXXXXX",
		},
		{
			default = 25,
			editor = "number",
			id = "max_res_amount_auto",
			max = 1000,
			min = 1,
			name = "Amount stored in stockpile auto",
			desc = "XXXXXXXXXXXXXX",
		},
		{
			default = 1000,
			editor = "number",
			id = "mine_time_animConcrete",
			max = 100000,
			min = 1,
			name = "Time to mine concrete anim",
			desc = "XXXXXXXXXXXXXX",
		},
		{
			default = 1500,
			editor = "number",
			id = "mine_time_idleConcrete",
			max = 100000,
			min = 1,
			name = "Time to mine concrete idle",
			desc = "XXXXXXXXXXXXXX",
		},
		{
			default = 2000,
			editor = "number",
			id = "mine_time_animMetals",
			max = 100000,
			min = 1,
			name = "Time to mine metal anim",
			desc = "XXXXXXXXXXXXXX",
		},
		{
			default = 3000,
			editor = "number",
			id = "mine_time_idleMetals",
			max = 100000,
			min = 1,
			name = "Time to mine metal idle",
			desc = "XXXXXXXXXXXXXX",
		},
		{
			default = 10000,
			editor = "number",
			id = "mine_time_animPreciousMetals",
			max = 100000,
			min = 1,
			name = "Time to mine precious metal anim",
			desc = "XXXXXXXXXXXXXX",
		},
		{
			default = 15000,
			editor = "number",
			id = "mine_time_idlePreciousMetals",
			max = 100000,
			min = 1,
			name = "Time to mine precious metal idle",
			desc = "XXXXXXXXXXXXXX",
		},
		{
			default = "true",
			editor = "bool",
			id = "visual_cues",
			name = "Paint ground around mine",
			desc = "mspaint 4eva",
		},
	},
})
