return {

PlaceObj("ModItemBuildingTemplate", {
  "name", "CloningVatsOut",
  "template_class", "CloningVats",
  "construction_cost_Metals", 50000,
  "construction_cost_Polymers", 20000,
  "construction_cost_Electronics", 10000,
  "build_points", 30000,
  "require_prefab", true,
  "is_tall", true,
  --"dome_spot", "Spire",
  "achievement", "FirstDomeSpire",
  "maintenance_resource_type", "Polymers",
  "maintenance_resource_amount", 3000,
  "display_name", "CloningVatsOut",
  "display_name_pl","Cloning Vats",
  "description","Creates Clones over time. Cloned Colonists grow and age twice as fast.",
  "build_category", "Dome Spires",
  "display_icon", "UI/Icons/Buildings/cloning_vats.tga",
  "build_pos", 4,
  "entity", "CloningVats",
  "encyclopedia_image", "UI/Encyclopedia/CloningVats.tga",
  "label1",  "OutsideBuildings",
  "palettes", "CloningVats",
  "demolish_sinking", range(15, 20),
  "demolish_tilt_angle", range(300, 720),
  "demolish_debris", 85,
  "electricity_consumption", 30000,
  "enabled_shift_2", false,
  "enabled_shift_3", false,
  "max_workers", 6,
  "specialist", "medic"
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "CloningVatsSpire",
  "template_class", "CloningVats",
  "construction_cost_Metals", 50000,
  "construction_cost_Polymers", 20000,
  "construction_cost_Electronics", 10000,
  "build_points", 30000,
  "require_prefab", true,
  "is_tall", true,
  "dome_spot", "Spire",
  "achievement", "FirstDomeSpire",
  "maintenance_resource_type", "Polymers",
  "maintenance_resource_amount", 3000,
  "display_name", "CloningVatsSpire",
  "display_name_pl","Cloning Vats",
  "description","Creates Clones over time. Cloned Colonists grow and age twice as fast.",
  "build_category", "Dome Spires",
  "display_icon", "UI/Icons/Buildings/cloning_vats.tga",
  "build_pos", 4,
  "entity", "CloningVats",
  "encyclopedia_image", "UI/Encyclopedia/CloningVats.tga",
  "label1",  "OutsideBuildings",
  "palettes", "CloningVats",
  "demolish_sinking", range(15, 20),
  "demolish_tilt_angle", range(300, 720),
  "demolish_debris", 85,
  "electricity_consumption", 30000,
  "enabled_shift_2", false,
  "enabled_shift_3", false,
  "max_workers", 6,
  "specialist", "medic"
}),

PlaceObj("ModItemBuildingTemplate", {
  "name",  "GardenAlleys_Medium*",
  "template_class",  "Service",
  "construction_cost_Concrete",  4000,
  "build_points",  1000,
  "show_decals_on_placement",  true,
  "use_demolished_state",  false,
  "display_name",  T({0, "Alleys*"}),
  "display_name_pl",  T({0, "Alleys*"}),
  "description",  T({    5145,    "A beautiful park with alleys and benches."  }),
  "build_category",  "Decorations",
  "display_icon",  "UI/Icons/Buildings/medium_alleys.tga",
  "build_pos",  6,
  "entity",  "GardenAlleys_04",
  "encyclopedia_image",  "UI/Encyclopedia/Alleys.tga",
  "entity2",  "GardenAlleys_05",
  "entity3",  "GardenAlleys_06",
  "label1",  "Decorations",
  "label2",  "OutsideBuildings",
  "on_off_button",  false,
  "prio_button",  false,
  "comfort_increase",  5000,
  "interest1",  "interestRelaxation",
  "interest2",  "interestExercise",
  "interest3",  "interestPlaying",
  "max_visitors",  3,
  "usable_by_children",  true,
  "label2", "OutsideBuildings",
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",  "Apartments*",
  "template_class",
  "Apartments",
  "construction_cost_Concrete",
  35000,
  "construction_cost_Polymers",
  10000,
  "build_points",
  18000,
  "is_tall",
  true,
  "upgrade1_id",
  "Appartments_HomeCollective",
  "upgrade1_display_name",
  T({
    5005,
    "Home Collective"
  }),
  "upgrade1_description",
  T({
    5006,
    "+<upgrade1_add_value_1> Service Comfort."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/home_collective_01.tga",
  "upgrade1_upgrade_cost_Polymers",
  5000,
  "upgrade1_mod_label_1",
  "Apartments",
  "upgrade1_mod_prop_id_1",
  "service_comfort",
  "upgrade1_add_value_1",
  10,
  "maintenance_resource_type",
  "Concrete",
  "maintenance_resource_amount",
  3000,
  "display_name",
  T({0, "Apartments*"}),
  "display_name_pl",
  T({0, "Apartments*"}),
  "description",
  T({
    5007,
    "Provides living space for Colonists. Cramped quarters grant less Comfort during rest."
  }),
  "build_category",
  "Habitats",
  "display_icon",
  "UI/Icons/Buildings/apartments.tga",
  "build_pos",
  2,
  "entity",
  "HiveHabitat",
  "encyclopedia_image",
  "UI/Encyclopedia/Apartments.tga",
  "entity2",
  "HiveHabitat_02",
  "entity3",
  "HiveHabitatDDE",
  "entitydlc3",
  "dde",
  "entity4",
  "HiveHabitatDDE_02",
  "entitydlc4",
  "dde",
  "label1",
  "OutsideBuildings",
  "palettes",
  "Apartments",
  "demolish_sinking",
  range(7, 15),
  "demolish_debris",
  90,
  "electricity_consumption",
  12000,
  "service_comfort",
  35000,
  "comfort_increase",
  4000,
  "capacity",
  24
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "Arcology*",
  "template_class",
  "Arcology",
  "construction_cost_Concrete",
  80000,
  "construction_cost_Polymers",
  10000,
  "build_points",
  30000,
  "require_prefab",
  true,
  "is_tall",
  true,
  --"dome_spot", "Spire",
  "achievement",
  "FirstDomeSpire",
  "upgrade1_id",
  "Arcology_HomeCollective",
  "upgrade1_display_name",
  T({
    5005,
    "Home Collective"
  }),
  "upgrade1_description",
  T({
    5006,
    "+<upgrade1_add_value_1> Service Comfort."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/home_collective_01.tga",
  "upgrade1_upgrade_cost_Polymers",
  10000,
  "upgrade1_mod_label_1",
  "Arcology",
  "upgrade1_mod_prop_id_1",
  "service_comfort",
  "upgrade1_add_value_1",
  10,
  "maintenance_resource_type",
  "Polymers",
  "maintenance_resource_amount",
  4000,
  "display_name",
  T({0, "Arcology*"}),
  "display_name_pl",
  T({0, "Arcologies*"}),
  "description",
  T({
    5009,
    "Provides living space for numerous Colonists, granting high Comfort."
  }),
  "build_category",
  "Dome Spires",
  "display_icon",
  "UI/Icons/Buildings/arcology.tga",
  "entity",
  "Arcology",
  "encyclopedia_image",
  "UI/Encyclopedia/Arcology.tga",
  "label1",
  "OutsideBuildings",
  "demolish_sinking",
  range(0, 0),
  "demolish_tilt_angle",
  range(0, 0),
  "demolish_debris",
  90,
  "spire_frame_entity",
  "ArcologyFrame",
  "electricity_consumption",
  20000,
  "service_comfort",
  60000,
  "comfort_increase",
  4000,
  "capacity",
  32
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "ShopsJewelry*",
  "template_class",
  "ServiceWorkplace",
  "construction_cost_Concrete",
  10000,
  "construction_cost_Polymers",
  2000,
  "build_points",
  3000,
  "upgrade1_id",
  "ShopJewelry_ServiceBots",
  "upgrade1_display_name",
  T({
    5020,
    "Service Bots"
  }),
  "upgrade1_description",
  T({
    5021,
    "This building no longer requires Workers and operates at <upgrade1_add_value_2> Performance."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/service_bots_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  10000,
  "upgrade1_mod_prop_id_1",
  "automation",
  "upgrade1_add_value_1",
  1,
  "upgrade1_mod_prop_id_2",
  "auto_performance",
  "upgrade1_add_value_2",
  100,
  "upgrade1_mod_prop_id_3",
  "max_workers",
  "upgrade1_mul_value_3",
  -100,
  "maintenance_resource_type",
  "Concrete",
  "consumption_resource_type",
  "Polymers",
  "consumption_amount",
  200,
  "consumption_type",
  2,
  "display_name",
  T({
    0,
    "Art Workshop*"
  }),
  "display_name_pl",
  T({
    0,
    "Art Workshops*"
  }),
  "description",
  T({
    5110,
    "A place to create and enjoy authentic Martian works of art. Consumes Polymers on each visit."
  }),
  "build_category",
  "Dome Services",
  "display_icon",
  "UI/Icons/Buildings/jewelry_store.tga",
  "build_pos",
  8,
  "entity",
  "ShopsJewelry",
  "encyclopedia_image",
  "UI/Encyclopedia/ArtWorkshop.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "Grocery",
  "demolish_sinking",
  range(10, 25),
  "demolish_debris",
  85,
  "service_comfort",
  80000,
  "comfort_increase",
  15000,
  "interest1",
  "interestLuxury",
  "interest2",
  "interestShopping",
  "max_visitors",
  8,
  "enabled_shift_3",
  false,
  "max_workers",
  1
}),

PlaceObj("ModItemBuildingTemplate", {
  "name",
  "Casino Complex*",
  "template_class",
  "CasinoComplex",
  "construction_cost_Concrete",
  40000,
  "construction_cost_Electronics",
  20000,
  "build_points",
  18000,
  "is_tall",
  true,
  "upgrade1_id",
  "Casino_ServiceBots",
  "upgrade1_display_name",
  T({
    5020,
    "Service Bots"
  }),
  "upgrade1_description",
  T({
    5021,
    "This building no longer requires Workers and operates at <upgrade1_add_value_2> Performance."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/service_bots_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  10000,
  "upgrade1_mod_prop_id_1",
  "automation",
  "upgrade1_add_value_1",
  1,
  "upgrade1_mod_prop_id_2",
  "auto_performance",
  "upgrade1_add_value_2",
  100,
  "upgrade1_mod_prop_id_3",
  "max_workers",
  "upgrade1_mul_value_3",
  -100,
  "maintenance_resource_type",
  "Electronics",
  "maintenance_resource_amount",
  2000,
  "display_name",
  T({
    0,
    "Casino Complex*"
  }),
  "display_name_pl",
  T({
    0,
    "Casino Complexes*"
  }),
  "description",
  T({
    5024,
    "A place of luxurious entertainment and questionable morals, helping to bring out the best of humanity."
  }),
  "build_category",
  "Dome Services",
  "display_icon",
  "UI/Icons/Buildings/casino_complex.tga",
  "build_pos",
  5,
  "entity",
  "Casino",
  "encyclopedia_image",
  "UI/Encyclopedia/CasinoComplex.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "Casino",
  "demolish_sinking",
  range(5, 10),
  "demolish_tilt_angle",
  range(600, 900),
  "demolish_debris",
  85,
  "electricity_consumption",
  5000,
  "service_comfort",
  70000,
  "comfort_increase",
  15000,
  "interest1",
  "interestLuxury",
  "interest2",
  "interestGaming",
  "interest3",
  "interestGambling",
  "interest4",
  "interestSocial",
  "max_visitors",
  10,
  "enabled_shift_3",
  false,
  "max_workers",
  3
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "Diner*",
  "template_class",
  "Diner",
  "construction_cost_Concrete",
  10000,
  "construction_cost_Metals",
  5000,
  "build_points",
  4000,
  "upgrade1_id",
  "Diner_ServiceBots",
  "upgrade1_display_name",
  T({
    5020,
    "Service Bots"
  }),
  "upgrade1_description",
  T({
    5021,
    "This building no longer requires Workers and operates at <upgrade1_add_value_2> Performance."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/service_bots_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  10000,
  "upgrade1_mod_prop_id_1",
  "automation",
  "upgrade1_add_value_1",
  1,
  "upgrade1_mod_prop_id_2",
  "auto_performance",
  "upgrade1_add_value_2",
  100,
  "upgrade1_mod_prop_id_3",
  "max_workers",
  "upgrade1_mul_value_3",
  -100,
  "maintenance_resource_type",
  "Concrete",
  "consumption_resource_type",
  "Food",
  "consumption_amount",
  200,
  "consumption_type",
  2,
  "consumption_resource_stockpile_spot_name",
  "Resourcepile",
  "display_name",
  T({0, "Diner*"}),
  "display_name_pl",
  T({0, "Diners*"}),
  "description",
  T({
    5044,
    "Serves the finest dishes on Mars. Now featuring non-plastic tableware."
  }),
  "build_category",
  "Dome Services",
  "display_icon",
  "UI/Icons/Buildings/dinner.tga",
  "build_pos",
  2,
  "entity",
  "Restaurant",
  "encyclopedia_image",
  "UI/Encyclopedia/Diner.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "Diner",
  "demolish_sinking",
  range(15, 20),
  "demolish_tilt_angle",
  range(120, 600),
  "electricity_consumption",
  2000,
  "service_comfort",
  60000,
  "interest1",
  "interestDining",
  "interest2",
  "interestSocial",
  "interest3",
  "needFood",
  "max_visitors",
  10,
  "usable_by_children",
  true,
  "enabled_shift_3",
  false,
  "max_workers",
  2
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "ElectronicsFactory*",
  "template_class",
  "ElectronicsFactory",
  "resource_produced1",
  "Electronics",
  "production_per_day1",
  9000,
  "construction_cost_Concrete",
  10000,
  "construction_cost_Metals",
  5000,
  "construction_cost_Electronics",
  15000,
  "build_points",
  7000,
  "require_prefab",
  true,
  "is_tall",
  true,
  "upgrade1_id",
  "ElectronicsFactory_FactoryAI",
  "upgrade1_display_name",
  T({5054, "Factory AI"}),
  "upgrade1_description",
  T({
    7667,
    "+<upgrade1_mul_value_1>% Production."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/factory_ai_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  5000,
  "upgrade1_upgrade_cost_MachineParts",
  2000,
  "upgrade1_mod_label_1",
  "ElectronicsFactory",
  "upgrade1_mod_prop_id_1",
  "production_per_day1",
  "upgrade1_mul_value_1",
  20,
  "upgrade2_id",
  "ElectronicsFactory_Automation",
  "upgrade2_display_name",
  T({5056, "Automation"}),
  "upgrade2_description",
  T({
    5057,
    "Decreases Workplaces by <abs(upgrade2_add_value_1)>."
  }),
  "upgrade2_icon",
  "UI/Icons/Upgrades/automation_01.tga",
  "upgrade2_upgrade_cost_Polymers",
  5000,
  "upgrade2_upgrade_cost_Electronics",
  5000,
  "upgrade2_mod_label_1",
  "ElectronicsFactory",
  "upgrade2_mod_prop_id_1",
  "max_workers",
  "upgrade2_add_value_1",
  -2,
  "upgrade3_id",
  "ElectronicsFactory_Amplify",
  "upgrade3_display_name",
  T({5028, "Amplify"}),
  "upgrade3_description",
  T({
    5058,
    "+<upgrade3_mul_value_1>% Production; +<power(upgrade3_add_value_2)> Consumption."
  }),
  "upgrade3_icon",
  "UI/Icons/Upgrades/amplify_01.tga",
  "upgrade3_upgrade_cost_Polymers",
  5000,
  "upgrade3_mod_label_1",
  "ElectronicsFactory",
  "upgrade3_mod_prop_id_1",
  "production_per_day1",
  "upgrade3_mul_value_1",
  25,
  "upgrade3_mod_label_2",
  "ElectronicsFactory",
  "upgrade3_mod_prop_id_2",
  "electricity_consumption",
  "upgrade3_add_value_2",
  20000,
  "maintenance_resource_type",
  "Electronics",
  "maintenance_resource_amount",
  3000,
  "consumption_resource_type",
  "PreciousMetals",
  "consumption_amount",
  300,
  "display_name",
  T({
    0,
    "Electronics Factory*"
  }),
  "display_name_pl",
  T({
    0,
    "Electronics Factories*"
  }),
  "description",
  T({
    5060,
    "Creates Electronics from Rare Metals."
  }),
  "build_category",
  "Production",
  "display_icon",
  "UI/Icons/Buildings/electronics_factory.tga",
  "build_pos",
  7,
  "entity",
  "ElectronicsFactory",
  "encyclopedia_image",
  "UI/Encyclopedia/ElectronicsFactory.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "ElectronicFactory",
  "demolish_sinking",
  range(5, 10),
  "demolish_tilt_angle",
  range(720, 1020),
  "demolish_debris",
  80,
  "electricity_consumption",
  8000,
  "enabled_shift_2",
  false,
  "enabled_shift_3",
  false,
  "max_workers",
  10,
  "specialist",
  "engineer"
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "ShopsElectronics*",
  "template_class",
  "ServiceWorkplace",
  "construction_cost_Concrete",
  10000,
  "construction_cost_Electronics",
  3000,
  "build_points",
  3000,
  "upgrade1_id",
  "ShopElectronics_ServiceBots",
  "upgrade1_display_name",
  T({
    5020,
    "Service Bots"
  }),
  "upgrade1_description",
  T({
    5021,
    "This building no longer requires Workers and operates at <upgrade1_add_value_2> Performance."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/service_bots_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  10000,
  "upgrade1_mod_prop_id_1",
  "automation",
  "upgrade1_add_value_1",
  1,
  "upgrade1_mod_prop_id_2",
  "auto_performance",
  "upgrade1_add_value_2",
  100,
  "upgrade1_mod_prop_id_3",
  "max_workers",
  "upgrade1_mul_value_3",
  -100,
  "maintenance_resource_type",
  "Concrete",
  "consumption_resource_type",
  "Electronics",
  "consumption_amount",
  200,
  "consumption_type",
  2,
  "consumption_resource_stockpile_spot_name",
  "Resourcepile",
  "display_name",
  T({
    0,
    "Electronics Store*"
  }),
  "display_name_pl",
  T({
    5066,
    "Electronics Stores"
  }),
  "description",
  T({
    5067,
    "Buy the latest and greatest gadgets Mars has to offer! Consumes Electronics on each visit."
  }),
  "build_category",
  "Dome Services",
  "display_icon",
  "UI/Icons/Buildings/electronics_store.tga",
  "build_pos",
  9,
  "entity",
  "ShopsElectronics",
  "encyclopedia_image",
  "UI/Encyclopedia/ElectronicsStore.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "SopsElectronics",
  "demolish_sinking",
  range(15, 25),
  "demolish_debris",
  85,
  "service_comfort",
  100000,
  "comfort_increase",
  20000,
  "interest1",
  "interestShopping",
  "interest2",
  "interestGaming",
  "max_visitors",
  8,
  "enabled_shift_3",
  false,
  "max_workers",
  1
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "Farm*",
  "template_class",
  "FarmConventional",
  "resource_produced1",
  "Food",
  "max_storage1",
  300000,
  "construction_cost_Concrete",
  8000,
  "build_points",
  2000,
  "is_tall",
  true,
  "upgrade1_id",
  "Farm_Automation",
  "upgrade1_display_name",
  T({5056, "Automation"}),
  "upgrade1_description",
  T({
    8044,
    "Decreases Workplaces by <abs(upgrade1_add_value_1)>."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/automation_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  5000,
  "upgrade1_mod_label_1",
  "Farm",
  "upgrade1_mod_prop_id_1",
  "max_workers",
  "upgrade1_add_value_1",
  -2,
  "display_name",
  T({0, "Farm*"}),
  "display_name_pl",
  T({5068, "Farms"}),
  "description",
  T({
    5069,
    "Produces Food. Consumes Water depending on crop type."
  }),
  "build_category",
  "Life-Support",
  "display_icon",
  "UI/Icons/Buildings/farm.tga",
  "build_pos",
  9,
  "entity",
  "Farm",
  "encyclopedia_image",
  "UI/Encyclopedia/Farm.tga",
  "label1",
  "OutsideBuildings",
  "color_modifier",
  RGBA(0, 248, 50, 255),
  "palettes",
  "Outside_06",
  "demolish_sinking",
  range(0, 0),
  "demolish_tilt_angle",
  range(300, 300),
  "electricity_consumption",
  0,
  "active_shift",
  1,
  "enabled_shift_2",
  false,
  "enabled_shift_3",
  false,
  "max_workers",
  6,
  "specialist",
  "botanist"
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "FountainLarge*",
  "template_class",
  "Service",
  "construction_cost_Concrete",
  4000,
  "build_points",
  1000,
  "use_demolished_state",
  false,
  "display_name",
  T({0, "Fountain*"}),
  "display_name_pl",
  T({5115, "Fountains"}),
  "description",
  T({
    5116,
    "A place for relaxation and recreation."
  }),
  "build_category",
  "Decorations",
  "display_icon",
  "UI/Icons/Buildings/large_fountain.tga",
  "build_pos",
  10,
  "entity",
  "GardenFountains_03",
  "encyclopedia_image",
  "UI/Encyclopedia/Fountain.tga",
  "label1",
  "Decorations",
  "label2", "OutsideBuildings",
  "on_off_button",
  false,
  "prio_button",
  false,
  "comfort_increase",
  5000,
  "interest1",
  "interestRelaxation",
  "interest2",
  "interestExercise",
  "interest3",
  "interestPlaying",
  "max_visitors",
  3,
  "usable_by_children",
  true
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "GardenNatural_Medium*",
  "template_class",
  "Service",
  "construction_cost_Concrete",
  4000,
  "build_points",
  1000,
  "use_demolished_state",
  false,
  "display_name",
  T({0, "Garden*"}),
  "display_name_pl",
  T({5150, "Gardens"}),
  "description",
  T({
    5151,
    "A recreational area with cultivated vegetation."
  }),
  "build_category",
  "Decorations",
  "display_icon",
  "UI/Icons/Buildings/medium_garden.tga",
  "build_pos",
  4,
  "entity",
  "GardenNatural_04",
  "encyclopedia_image",
  "UI/Encyclopedia/Garden.tga",
  "entity2",
  "GardenNatural_05",
  "entity3",
  "GardenNatural_06",
  "label1",
  "Decorations",
  "label2", "OutsideBuildings",
  "on_off_button",
  false,
  "prio_button",
  false,
  "comfort_increase",
  5000,
  "interest1",
  "interestRelaxation",
  "interest2",
  "interestExercise",
  "interest3",
  "interestPlaying",
  "max_visitors",
  3,
  "usable_by_children",
  true
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "ShopsFood*",
  "template_class",
  "Grocery",
  "construction_cost_Concrete",
  10000,
  "build_points",
  3000,
  "upgrade1_id",
  "ShopFood_ServiceBots",
  "upgrade1_display_name",
  T({
    5020,
    "Service Bots"
  }),
  "upgrade1_description",
  T({
    5021,
    "This building no longer requires Workers and operates at <upgrade1_add_value_2> Performance."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/service_bots_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  10000,
  "upgrade1_mod_prop_id_1",
  "automation",
  "upgrade1_add_value_1",
  1,
  "upgrade1_mod_prop_id_2",
  "auto_performance",
  "upgrade1_add_value_2",
  100,
  "upgrade1_mod_prop_id_3",
  "max_workers",
  "upgrade1_mul_value_3",
  -100,
  "maintenance_resource_type",
  "Concrete",
  "consumption_resource_type",
  "Food",
  "consumption_amount",
  200,
  "consumption_type",
  2,
  "consumption_resource_stockpile_spot_name",
  "Resourcepile",
  "display_name",
  T({0, "Grocer*"}),
  "display_name_pl",
  T({5097, "Grocers"}),
  "description",
  T({
    5098,
    "Distributes hot meals and fresh produce."
  }),
  "build_category",
  "Dome Services",
  "display_icon",
  "UI/Icons/Buildings/grocery.tga",
  "build_pos",
  7,
  "entity",
  "ShopsFood",
  "encyclopedia_image",
  "UI/Encyclopedia/Grocer.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "Grocery",
  "demolish_sinking",
  range(5, 10),
  "demolish_debris",
  85,
  "service_comfort",
  50000,
  "interest1",
  "needFood",
  "interest2",
  "interestShopping",
  "max_visitors",
  8,
  "usable_by_children",
  true,
  "enabled_shift_3",
  false,
  "max_workers",
  1
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "HangingGardens*",
  "template_class",
  "HangingGardens",
  "construction_cost_Concrete",
  40000,
  "construction_cost_Polymers",
  10000,
  "build_points",
  30000,
  "require_prefab",
  true,
  "is_tall",
  true,
  --"dome_spot", "Spire",
  "achievement",
  "FirstDomeSpire",
  "maintenance_resource_type",
  "Concrete",
  "maintenance_resource_amount",
  4000,
  "display_name",
  T({
    0,
    "Hanging Gardens*"
  }),
  "display_name_pl",
  T({
    3535,
    "Hanging Gardens"
  }),
  "description",
  T({
    5099,
    "A beautiful park complex. Increases the Comfort of all Residences in the Dome."
  }),
  "build_category",
  "Dome Spires",
  "display_icon",
  "UI/Icons/Buildings/hanging_gardens.tga",
  "build_pos",
  2,
  "entity",
  "HangingGardens",
  "dome_comfort",
  30000,
  "encyclopedia_image",
  "UI/Encyclopedia/HangingGardens.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "Outside_10",
  "demolish_sinking",
  range(0, 0),
  "demolish_tilt_angle",
  range(0, 0),
  "water_consumption",
  2000,
  "air_consumption",
  0,
  "service_comfort",
  100000,
  "comfort_increase",
  15000,
  "interest1",
  "interestRelaxation",
  "interest2",
  "interestExercise",
  "interest3",
  "interestPlaying",
  "max_visitors",
  20
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "HydroponicFarm*",
  "template_class",
  "FarmHydroponic",
  "resource_produced1",
  "Food",
  "max_storage1",
  100000,
  "construction_cost_Metals",
  4000,
  "construction_cost_Polymers",
  2000,
  "build_points",
  2000,
  "is_tall",
  true,
  "upgrade1_id",
  "HydroponicFarm_Automation",
  "upgrade1_display_name",
  T({5056, "Automation"}),
  "upgrade1_description",
  T({
    5100,
    "Decreases Workplaces by <abs(upgrade1_add_value_1)>."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/automation_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  2000,
  "upgrade1_mod_label_1",
  "HydroponicFarm",
  "upgrade1_mod_prop_id_1",
  "max_workers",
  "upgrade1_add_value_1",
  -1,
  "maintenance_resource_type",
  "Metals",
  "display_name",
  T({
    0,
    "Hydroponic Farm*"
  }),
  "display_name_pl",
  T({
    5102,
    "Hydroponic Farms"
  }),
  "description",
  T({
    5069,
    "Produces Food. Consumes Water depending on crop type."
  }),
  "build_category",
  "Life-Support",
  "display_icon",
  "UI/Icons/Buildings/hydroponics_farm.tga",
  "build_pos",
  8,
  "entity",
  "HydroponicFarm",
  "encyclopedia_image",
  "UI/Encyclopedia/HydroponicFarm.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "Outside_06",
  "demolish_sinking",
  range(10, 25),
  "electricity_consumption",
  5000,
  "active_shift",
  1,
  "enabled_shift_2",
  false,
  "enabled_shift_3",
  false,
  "max_workers",
  3,
  "specialist",
  "botanist",
  "hydroponic",
  true
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "Infirmary*",
  "template_class",
  "Infirmary",
  "construction_cost_Concrete",
  15000,
  "build_points",
  3000,
  "upgrade1_id",
  "Infirmary_RejuvenationTreatment",
  "upgrade1_display_name",
  T({
    5103,
    "Rejuvenation Treatment"
  }),
  "upgrade1_description",
  T({
    8045,
    "Improves Service Comfort. Colonists can visit for Relaxation."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/rejuvenation_treatment_01.tga",
  "upgrade1_upgrade_cost_Polymers",
  5000,
  "upgrade1_mod_prop_id_1",
  "service_comfort",
  "upgrade1_add_value_1",
  30,
  "maintenance_resource_type",
  "Concrete",
  "display_name",
  T({0, "Infirmary*"}),
  "display_name_pl",
  T({
    5106,
    "Infirmaries"
  }),
  "description",
  T({
    5107,
    "Visitors will recover Health and Sanity as long as they are not starving, dehydrated, freezing or suffocating. A Dome with a Medical Building has lower minimum Comfort requirement for births."
  }),
  "build_category",
  "Dome Services",
  "display_icon",
  "UI/Icons/Buildings/infirmary.tga",
  "build_pos",
  3,
  "entity",
  "Infirmary",
  "encyclopedia_image",
  "UI/Encyclopedia/Infirmary.tga",
  "label1",
  "OutsideBuildings",
  "label2",
  "MedicalBuilding",
  "palettes",
  "Infirmary",
  "demolish_sinking",
  range(8, 18),
  "demolish_tilt_angle",
  range(600, 900),
  "demolish_debris",
  80,
  "electricity_consumption",
  2000,
  "health_change",
  20000,
  "sanity_change",
  10000,
  "interest1",
  "needMedical",
  "usable_by_children",
  true,
  "enabled_shift_3",
  false,
  "max_workers",
  2,
  "specialist",
  "medic"
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "Lake*",
  "template_class",
  "Service",
  "construction_cost_Concrete",
  3000,
  "build_points",
  1000,
  "upgrade1_upgrade_cost_Concrete",
  4000,
  "use_demolished_state",
  false,
  "display_name",
  T({0, "Lake*"}),
  "display_name_pl",
  T({5112, "Lakes"}),
  "description",
  T({
    5113,
    "A large lake with refreshingly cool water."
  }),
  "build_category",
  "Decorations",
  "display_icon",
  "UI/Icons/Buildings/lake.tga",
  "build_pos",
  8,
  "entity",
  "GardenLake",
  "encyclopedia_image",
  "UI/Encyclopedia/Lake.tga",
  "label1",
  "Decorations",
  "label2", "OutsideBuildings",
  "on_off_button",
  false,
  "prio_button",
  false,
  "comfort_increase",
  5000,
  "interest1",
  "interestRelaxation",
  "interest2",
  "interestExercise",
  "interest3",
  "interestPlaying",
  "max_visitors",
  3,
  "usable_by_children",
  true
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "LivingQuarters*",
  "template_class",
  "LivingQuarters",
  "construction_cost_Concrete",
  10000,
  "build_points",
  6000,
  "show_decals_on_placement",
  true,
  "upgrade1_id",
  "LivingQuarters_HomeCollective",
  "upgrade1_display_name",
  T({
    5005,
    "Home Collective"
  }),
  "upgrade1_description",
  T({
    5006,
    "+<upgrade1_add_value_1> Service Comfort."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/home_collective_01.tga",
  "upgrade1_upgrade_cost_Polymers",
  5000,
  "upgrade1_mod_label_1",
  "LivingQuarters",
  "upgrade1_mod_prop_id_1",
  "service_comfort",
  "upgrade1_add_value_1",
  10,
  "maintenance_resource_type",
  "Concrete",
  "display_name",
  T({
    0,
    "Living Quarters*"
  }),
  "display_name_pl",
  T({
    3532,
    "Living Quarters"
  }),
  "description",
  T({
    5122,
    "Provides living space. Resting residents recover Comfort faster compared to other Residences."
  }),
  "build_category",
  "Habitats",
  "display_icon",
  "UI/Icons/Buildings/living_quarters.tga",
  "entity",
  "LivingQuarters_01",
  "encyclopedia_image",
  "UI/Encyclopedia/LivingQuarters.tga",
  "entity2",
  "LivingQuarters_02",
  "entity3",
  "LivingQuarters_03",
  "entity4",
  "LivingQuartersDDE_01",
  "entitydlc4",
  "dde",
  "entity5",
  "LivingQuartersDDE_02",
  "entitydlc5",
  "dde",
  "entity6",
  "LivingQuartersDDE_03",
  "entitydlc6",
  "dde",
  "label1",
  "OutsideBuildings",
  "palettes",
  "Living",
  "demolish_sinking",
  range(5, 10),
  "demolish_debris",
  85,
  "service_comfort",
  50000,
  "comfort_increase",
  6000,
  "capacity",
  14
}),

PlaceObj("ModItemBuildingTemplate", {
  "name",
  "MachinePartsFactory*",
  "template_class",
  "MachinePartsFactory",
  "resource_produced1",
  "MachineParts",
  "production_per_day1",
  12000,
  "construction_cost_Concrete",
  10000,
  "construction_cost_Metals",
  10000,
  "construction_cost_Electronics",
  2000,
  "build_points",
  7000,
  "require_prefab",
  true,
  "upgrade1_id",
  "MachinePartsFactory_FactoryAI",
  "upgrade1_display_name",
  T({5054, "Factory AI"}),
  "upgrade1_description",
  T({
    7668,
    "+<upgrade1_mul_value_1>% Production."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/factory_ai_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  5000,
  "upgrade1_upgrade_cost_MachineParts",
  2000,
  "upgrade1_mod_label_1",
  "MachinePartsFactory",
  "upgrade1_mod_prop_id_1",
  "production_per_day1",
  "upgrade1_mul_value_1",
  20,
  "upgrade2_id",
  "MachinePartsFactory_Automation",
  "upgrade2_display_name",
  T({5056, "Automation"}),
  "upgrade2_description",
  T({
    5057,
    "Decreases Workplaces by <abs(upgrade2_add_value_1)>."
  }),
  "upgrade2_icon",
  "UI/Icons/Upgrades/automation_01.tga",
  "upgrade2_upgrade_cost_Polymers",
  5000,
  "upgrade2_upgrade_cost_Electronics",
  5000,
  "upgrade2_mod_label_1",
  "MachinePartsFactory",
  "upgrade2_mod_prop_id_1",
  "max_workers",
  "upgrade2_add_value_1",
  -2,
  "upgrade3_id",
  "MachinePartsFactory_Amplify",
  "upgrade3_display_name",
  T({5028, "Amplify"}),
  "upgrade3_description",
  T({
    5058,
    "+<upgrade3_mul_value_1>% Production; +<power(upgrade3_add_value_2)> Consumption."
  }),
  "upgrade3_icon",
  "UI/Icons/Upgrades/amplify_01.tga",
  "upgrade3_upgrade_cost_Polymers",
  5000,
  "upgrade3_mod_label_1",
  "MachinePartsFactory",
  "upgrade3_mod_prop_id_1",
  "production_per_day1",
  "upgrade3_mul_value_1",
  25,
  "upgrade3_mod_label_2",
  "MachinePartsFactory",
  "upgrade3_mod_prop_id_2",
  "electricity_consumption",
  "upgrade3_add_value_2",
  20000,
  "maintenance_resource_type",
  "Electronics",
  "maintenance_resource_amount",
  2000,
  "consumption_resource_type",
  "Metals",
  "display_name",
  T({
    0,
    "Machine Parts Factory*"
  }),
  "display_name_pl",
  T({
    5131,
    "Machine Parts Factories"
  }),
  "description",
  T({
    5132,
    "Produces Machine Parts from Metals."
  }),
  "build_category",
  "Production",
  "display_icon",
  "UI/Icons/Buildings/machine_parts_factory.tga",
  "build_pos",
  8,
  "entity",
  "MachinePartsFactory",
  "encyclopedia_image",
  "UI/Encyclopedia/MachinePartsFactory.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "MachineParts",
  "demolish_sinking",
  range(15, 25),
  "demolish_debris",
  85,
  "electricity_consumption",
  30000,
  "enabled_shift_2",
  false,
  "enabled_shift_3",
  false,
  "specialist",
  "engineer"
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "MartianUniversity*",
  "template_class",
  "MartianUniversity",
  "construction_cost_Concrete",
  30000,
  "construction_cost_Metals",
  10000,
  "construction_cost_Electronics",
  20000,
  "build_points",
  12000,
  "maintenance_resource_type",
  "Electronics",
  "maintenance_resource_amount",
  3000,
  "display_name",
  T({
    0,
    "Martian University*"
  }),
  "display_name_pl",
  T({
    5138,
    "Martian Universities"
  }),
  "description",
  T({
    5139,
    "Trains Specialists using modern remote learning techniques."
  }),
  "build_category",
  "Habitats",
  "display_icon",
  "UI/Icons/Buildings/martian_university.tga",
  "build_pos",
  10,
  "entity",
  "University",
  "encyclopedia_image",
  "UI/Encyclopedia/MartianUniversity.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "University",
  "demolish_sinking",
  range(10, 20),
  "demolish_debris",
  85,
  "electricity_consumption",
  15000,
  "enabled_shift_1",
  false,
  "enabled_shift_3",
  false,
  "evaluation_points",
  300
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "MedicalCenter*",
  "template_class",
  "MedicalCenter",
  "construction_cost_Concrete",
  30000,
  "construction_cost_Metals",
  30000,
  "construction_cost_Polymers",
  10000,
  "build_points",
  30000,
  "require_prefab",
  true,
  "is_tall",
  true,
  --"dome_spot", "Spire",
  "achievement",
  "FirstDomeSpire",
  "upgrade1_id",
  "MedicalCenter_HolographicScanner",
  "upgrade1_display_name",
  T({
    5140,
    "Holographic Scanner"
  }),
  "upgrade1_description",
  T({
    5141,
    "Increases Birth Rate in the Dome."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/holographic_scanner_01.tga",
  "upgrade1_upgrade_cost_Polymers",
  10000,
  "upgrade1_upgrade_cost_Electronics",
  5000,
  "upgrade1_mod_target_1",
  "parent_dome",
  "upgrade1_mod_label_1",
  "Colonist",
  "upgrade1_mod_prop_id_1",
  "birth_comfort_modifier",
  "upgrade1_add_value_1",
  30,
  "upgrade2_id",
  "MedicalCenter_RejuvenationTreatment",
  "upgrade2_display_name",
  T({
    5103,
    "Rejuvenation Treatment"
  }),
  "upgrade2_description",
  T({
    5104,
    "Improves Service Comfort. Colonists can visit for Relaxation"
  }),
  "upgrade2_icon",
  "UI/Icons/Upgrades/rejuvenation_treatment_01.tga",
  "upgrade2_upgrade_cost_Polymers",
  10000,
  "upgrade2_mod_label_1",
  "MedicalCenter",
  "upgrade2_mod_prop_id_1",
  "salvage_modifier",
  "upgrade2_mod_label_2",
  "MedicalCenter",
  "upgrade2_mod_prop_id_2",
  "service_comfort",
  "upgrade2_add_value_2",
  15,
  "maintenance_resource_type",
  "Polymers",
  "maintenance_resource_amount",
  3000,
  "display_name",
  T({
    0,
    "Medical Center*"
  }),
  "display_name_pl",
  T({
    5142,
    "Medical Centers"
  }),
  "description",
  T({
    5143,
    "Visitors will recover Health and Sanity as long as they are not starving, dehydrated, freezing or suffocating. Larger capacity and more effective than the Infirmary. A Dome with a Medical Building has lower minimum Comfort requirement for births."
  }),
  "build_category",
  "Dome Spires",
  "display_icon",
  "UI/Icons/Buildings/medical_center.tga",
  "build_pos",
  7,
  "entity",
  "MedicalCenter",
  "encyclopedia_image",
  "UI/Encyclopedia/MedicalCenter.tga",
  "label1",
  "OutsideBuildings",
  "label2",
  "MedicalBuilding",
  "palettes",
  "Outside_02",
  "demolish_sinking",
  range(10, 12),
  "demolish_debris",
  80,
  "electricity_consumption",
  20000,
  "health_change",
  50000,
  "sanity_change",
  15000,
  "service_comfort",
  70000,
  "comfort_increase",
  15000,
  "interest1",
  "needMedical",
  "max_visitors",
  10,
  "usable_by_children",
  true,
  "enabled_shift_3",
  false,
  "max_workers",
  3,
  "specialist",
  "medic"
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "NetworkNode*",
  "template_class",
  "NetworkNode",
  "construction_cost_Concrete",
  50000,
  "construction_cost_Metals",
  50000,
  "construction_cost_Electronics",
  20000,
  "build_points",
  30000,
  "require_prefab",
  true,
  "is_tall",
  true,
  --"dome_spot", "Spire",
  "achievement",
  "FirstDomeSpire",
  "upgrade1_id",
  "NetworkNode_Amplify",
  "upgrade1_display_name",
  T({5028, "Amplify"}),
  "upgrade1_description",
  T({
    5176,
    "+<upgrade1_mul_value_2>% Performance, +<power(upgrade1_add_value_1)> Consumption."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/amplify_01.tga",
  "upgrade1_upgrade_cost_Polymers",
  10000,
  "upgrade1_mod_label_1",
  "NetworkNode",
  "upgrade1_mod_prop_id_1",
  "electricity_consumption",
  "upgrade1_add_value_1",
  20000,
  "upgrade1_mod_label_2",
  "NetworkNode",
  "upgrade1_mod_prop_id_2",
  "performance",
  "upgrade1_mul_value_2",
  25,
  "maintenance_resource_type",
  "Electronics",
  "maintenance_resource_amount",
  3000,
  "display_name",
  T({
    0,
    "Network Node*"
  }),
  "display_name_pl",
  T({
    5177,
    "Network Nodes"
  }),
  "description",
  T({
    5178,
    "Increases the overall Research output of the Dome."
  }),
  "build_category",
  "Dome Spires",
  "display_icon",
  "UI/Icons/Buildings/network_node.tga",
  "build_pos",
  5,
  "entity",
  "NetworkNode",
  "encyclopedia_image",
  "UI/Encyclopedia/NetworkNode.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "NetworkNode",
  "demolish_sinking",
  range(5, 10),
  "demolish_tilt_angle",
  range(60, 300),
  "electricity_consumption",
  20000,
  "enabled_shift_2",
  false,
  "enabled_shift_3",
  false,
  "max_workers",
  6,
  "specialist",
  "scientist"
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "Nursery*",
  "template_class",
  "Nursery",
  "construction_cost_Concrete",
  10000,
  "build_points",
  4000,
  "maintenance_resource_type",
  "Concrete",
  "display_name",
  T({0, "Nursery*"}),
  "display_name_pl",
  T({5180, "Nurseries"}),
  "description",
  T({
    5181,
    "Provides living space for children."
  }),
  "build_category",
  "Habitats",
  "display_icon",
  "UI/Icons/Buildings/nursery.tga",
  "build_pos",
  5,
  "entity",
  "Nursery",
  "encyclopedia_image",
  "UI/Encyclopedia/Nursery.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "KinderGarden",
  "demolish_sinking",
  range(10, 15),
  "electricity_consumption",
  2000,
  "service_comfort",
  60000,
  "comfort_increase",
  5000,
  "capacity",
  8,
  "children_only",
  true
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "OpenAirGym*",
  "template_class",
  "OpenAirGym",
  "construction_cost_Metals",
  10000,
  "construction_cost_Polymers",
  8000,
  "build_points",
  3000,
  "display_name",
  T({
    0,
    "Open Air Gym*"
  }),
  "display_name_pl",
  T({
    5186,
    "Open Air Gyms"
  }),
  "description",
  T({
    5187,
    "Visitors recover a small amount of Health and may become Fit."
  }),
  "build_category",
  "Dome Services",
  "display_icon",
  "UI/Icons/Buildings/open_air_gym.tga",
  "build_pos",
  4,
  "entity",
  "OpenAirGym",
  "encyclopedia_image",
  "UI/Encyclopedia/OpenAirGym.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "Gym",
  "demolish_sinking",
  range(0, 0),
  "health_change",
  10000,
  "service_comfort",
  50000,
  "interest1",
  "interestExercise",
  "interest2",
  "interestSocial",
  "max_visitors",
  10,
  "visit_duration",
  3
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "Playground*",
  "template_class",
  "Playground",
  "construction_cost_Polymers",
  8000,
  "build_points",
  3000,
  "display_name",
  T({0, "Playground*"}),
  "display_name_pl",
  T({
    5197,
    "Playgrounds"
  }),
  "description",
  T({
    5198,
    "Cultivates Perks in Children through special nurturing programs."
  }),
  "build_category",
  "Habitats",
  "display_icon",
  "UI/Icons/Buildings/playground.tga",
  "build_pos",
  6,
  "entity",
  "Playground",
  "encyclopedia_image",
  "UI/Encyclopedia/Playground.tga",
  "label1",
  "OutsideBuildings",
  "on_off_button",
  false,
  "prio_button",
  false,
  "palettes",
  "KinderGarden",
  "demolish_sinking",
  range(0, 0),
  "demolish_debris",
  80,
  "sanity_change",
  10000,
  "service_comfort",
  80000,
  "comfort_increase",
  15000,
  "interest1",
  "interestPlaying",
  "usable_by_children",
  true,
  "children_only",
  true
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "ResearchLab*",
  "template_class",
  "BaseResearchLab",
  "construction_cost_Concrete",
  15000,
  "construction_cost_Electronics",
  8000,
  "build_points",
  6000,
  "is_tall",
  true,
  "upgrade1_id",
  "ResearchLab_ZeroSpace",
  "upgrade1_display_name",
  T({
    5232,
    "Zero-Space Computing"
  }),
  "upgrade1_description",
  T({
    5233,
    "+<upgrade1_mul_value_1>% Production."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/zero_space_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  5000,
  "upgrade1_mod_prop_id_1",
  "ResearchPointsPerDay",
  "upgrade1_mul_value_1",
  25,
  "upgrade2_id",
  "ResearchLab_Amplify",
  "upgrade2_display_name",
  T({5028, "Amplify"}),
  "upgrade2_description",
  T({
    5234,
    "+<upgrade2_mul_value_2>% Production; +<power(upgrade2_add_value_1)> Consumption."
  }),
  "upgrade2_icon",
  "UI/Icons/Upgrades/amplify_01.tga",
  "upgrade2_upgrade_cost_Polymers",
  2000,
  "upgrade2_mod_prop_id_1",
  "electricity_consumption",
  "upgrade2_add_value_1",
  10000,
  "upgrade2_mod_prop_id_2",
  "ResearchPointsPerDay",
  "upgrade2_mul_value_2",
  25,
  "maintenance_resource_type",
  "Electronics",
  "display_name",
  T({
    0,
    "Research Lab*"
  }),
  "display_name_pl",
  T({
    5236,
    "Research Labs"
  }),
  "description",
  T({
    5237,
    "Generates Research."
  }),
  "build_category",
  "Habitats",
  "display_icon",
  "UI/Icons/Buildings/academy_of_science.tga",
  "build_pos",
  8,
  "entity",
  "Academy",
  "encyclopedia_image",
  "UI/Encyclopedia/ResearchLab.tga",
  "label1",
  "OutsideBuildings",
  "label2",
  "ResearchBuildings",
  "palettes",
  "ResearchLab",
  "demolish_sinking",
  range(5, 10),
  "demolish_debris",
  80,
  "electricity_consumption",
  5000,
  "enabled_shift_2",
  false,
  "enabled_shift_3",
  false,
  "max_workers",
  3,
  "specialist",
  "scientist",
  "ResearchPointsPerDay",
  500
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "Sanatorium*",
  "template_class",
  "Sanatorium",
  "construction_cost_Concrete",
  50000,
  "construction_cost_Metals",
  20000,
  "construction_cost_Polymers",
  10000,
  "build_points",
  30000,
  "require_prefab",
  true,
  "is_tall",
  true,
  --"dome_spot", "Spire",
  "achievement",
  "FirstDomeSpire",
  "upgrade1_id",
  "Sanatorium_BehavioralMelding",
  "upgrade1_display_name",
  T({
    5243,
    "Behavioral Melding"
  }),
  "upgrade1_description",
  T({
    5244,
    "Replaces flaws with Perks for visitors."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/behavioral_melding_01.tga",
  "upgrade1_upgrade_cost_Polymers",
  10000,
  "upgrade1_upgrade_cost_Electronics",
  10000,
  "maintenance_resource_type",
  "Polymers",
  "maintenance_resource_amount",
  2000,
  "display_name",
  T({0, "Sanatorium*"}),
  "display_name_pl",
  T({
    5245,
    "Sanatoriums"
  }),
  "description",
  T({
    5246,
    "Treats Colonists for flaws through advanced and (mostly humane) medical practices."
  }),
  "build_category",
  "Dome Spires",
  "display_icon",
  "UI/Icons/Buildings/sanatorium.tga",
  "build_pos",
  7,
  "entity",
  "Sanatorium",
  "encyclopedia_image",
  "UI/Encyclopedia/Sanatorium.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "Sanatorium",
  "demolish_sinking",
  range(5, 15),
  "electricity_consumption",
  20000,
  "enabled_shift_1",
  false,
  "enabled_shift_3",
  false,
  "max_visitors",
  4,
  "evaluation_points",
  200,
  "trait1",
  "Gambler",
  "trait2",
  "Alcoholic",
  "trait3",
  "Glutton"
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "School*",
  "template_class",
  "School",
  "construction_cost_Concrete",
  25000,
  "construction_cost_Electronics",
  10000,
  "build_points",
  9000,
  "maintenance_resource_type",
  "Electronics",
  "maintenance_resource_amount",
  2000,
  "display_name",
  T({0, "School*"}),
  "display_name_pl",
  T({5248, "Schools"}),
  "description",
  T({
    5249,
    "Cultivates desired Perks in children using modern remote learning techniques."
  }),
  "build_category",
  "Habitats",
  "display_icon",
  "UI/Icons/Buildings/school.tga",
  "build_pos",
  7,
  "entity",
  "School",
  "encyclopedia_image",
  "UI/Encyclopedia/School.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "School",
  "demolish_sinking",
  range(5, 10),
  "demolish_debris",
  85,
  "enabled_shift_3",
  false,
  "usable_by_children",
  true,
  "children_only",
  true,
  "gain_point",
  10,
  "trait1",
  "Survivor",
  "trait2",
  "Composed",
  "trait3",
  "Nerd"
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "ScienceInstitute*",
  "template_class",
  "BaseResearchLab",
  "construction_cost_Concrete",
  30000,
  "construction_cost_Polymers",
  10000,
  "construction_cost_Electronics",
  20000,
  "build_points",
  12000,
  "is_tall",
  true,
  "upgrade1_id",
  "ScienceInsitiute_ZeroSpace",
  "upgrade1_display_name",
  T({
    5232,
    "Zero-Space Computing"
  }),
  "upgrade1_description",
  T({
    5233,
    "+<upgrade1_mul_value_1>% Production."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/zero_space_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  10000,
  "upgrade1_mod_label_1",
  "ScienceInstitute",
  "upgrade1_mod_prop_id_1",
  "ResearchPointsPerDay",
  "upgrade1_mul_value_1",
  25,
  "upgrade2_id",
  "ScienceInstitute_Amplify",
  "upgrade2_display_name",
  T({5028, "Amplify"}),
  "upgrade2_description",
  T({
    5250,
    "+<upgrade2_mul_value_2>% Production; +<power(upgrade2_add_value_1)> Consumption."
  }),
  "upgrade2_icon",
  "UI/Icons/Upgrades/amplify_01.tga",
  "upgrade2_upgrade_cost_Polymers",
  5000,
  "upgrade2_mod_label_1",
  "ScienceInstitute",
  "upgrade2_mod_prop_id_1",
  "electricity_consumption",
  "upgrade2_add_value_1",
  20000,
  "upgrade2_mod_label_2",
  "ScienceInstitute",
  "upgrade2_mod_prop_id_2",
  "ResearchPointsPerDay",
  "upgrade2_mul_value_2",
  50,
  "maintenance_resource_type",
  "Electronics",
  "maintenance_resource_amount",
  4000,
  "display_name",
  T({
    0,
    "Science Institute*"
  }),
  "display_name_pl",
  T({
    5252,
    "Science Institutes"
  }),
  "description",
  T({
    5253,
    "Generates Research faster than a Research Lab."
  }),
  "build_category",
  "Habitats",
  "display_icon",
  "UI/Icons/Buildings/research_lab.tga",
  "build_pos",
  9,
  "entity",
  "ScienceInstitute",
  "encyclopedia_image",
  "UI/Encyclopedia/ScienceInstitute.tga",
  "label1",
  "OutsideBuildings",
  "label2",
  "ResearchBuildings",
  "palettes",
  "Outside_07",
  "demolish_sinking",
  range(5, 15),
  "electricity_consumption",
  15000,
  "enabled_shift_2",
  false,
  "enabled_shift_3",
  false,
  "max_workers",
  8,
  "specialist",
  "scientist"
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",  "SecurityStation*",
  "template_class",  "SecurityStation",
  "construction_cost_Concrete",  15000,
  "construction_cost_Metals",  5000,
  "build_points",  3000,
  "is_tall",  true,
  "maintenance_resource_type",  "Concrete",
  "display_name", "Security Station*",
  "display_name_pl", "Security Stations",
  "description", "Counters crime created by Renegades and reduces Sanity loss from disasters for all residents in the Dome.",
  "build_category",  "Dome Services",
  "display_icon",  "UI/Icons/Buildings/security_station.tga",
  "build_pos",  6,
  "entity",  "SecurityCenter",
  "encyclopedia_image",  "UI/Encyclopedia/SecurityStation.tga",
  "label1",  "OutsideBuildings",
  "palettes",  "SecurityStation",
  "demolish_sinking",  range(5, 10),
  "demolish_debris",  80,
  "electricity_consumption",  2000,
  "max_workers",  3,
  "specialist",  "security",
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "GardenAlleys_Small*",
  "template_class",
  "Service",
  "construction_cost_Concrete",
  2000,
  "build_points",
  500,
  "show_decals_on_placement",
  true,
  "use_demolished_state",
  false,
  "display_name",
  T({
    0,
    "Small Alleys*"
  }),
  "display_name_pl",
  T({
    5262,
    "Small Alleys"
  }),
  "description",
  T({
    5145,
    "A beautiful park with alleys and benches."
  }),
  "build_category",
  "Decorations",
  "display_icon",
  "UI/Icons/Buildings/small_alleys.tga",
  "build_pos",
  5,
  "entity",
  "GardenAlleys_01",
  "encyclopedia_image",
  "UI/Encyclopedia/SmallAlleys.tga",
  "entity2",
  "GardenAlleys_02",
  "entity3",
  "GardenAlleys_03",
  "label1",
  "Decorations",
  "label2", "OutsideBuildings",
  "on_off_button",
  false,
  "prio_button",
  false,
  "comfort_increase",
  5000,
  "interest1",
  "interestRelaxation",
  "interest2",
  "interestExercise",
  "interest3",
  "interestPlaying",
  "max_visitors",
  1,
  "usable_by_children",
  true
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "FountainSmall*",
  "template_class",
  "Service",
  "construction_cost_Concrete",
  2000,
  "build_points",
  500,
  "use_demolished_state",
  false,
  "display_name",
  T({
    0,
    "Small Fountain*"
  }),
  "display_name_pl",
  T({
    5264,
    "Small Fountains"
  }),
  "description",
  T({
    5116,
    "A place for relaxation and recreation."
  }),
  "build_category",
  "Decorations",
  "display_icon",
  "UI/Icons/Buildings/small_fountain.tga",
  "build_pos",
  9,
  "entity",
  "GardenFountains_01",
  "encyclopedia_image",
  "UI/Encyclopedia/SmallFountain.tga",
  "entity2",
  "GardenFountains_02",
  "label1",
  "Decorations",
  "label2", "OutsideBuildings",
  "on_off_button",
  false,
  "prio_button",
  false,
  "comfort_increase",
  5000,
  "interest1",
  "interestRelaxation",
  "interest2",
  "interestExercise",
  "interest3",
  "interestPlaying",
  "max_visitors",
  1,
  "usable_by_children",
  true
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "GardenNatural_Small*",
  "template_class",
  "Service",
  "construction_cost_Concrete",
  2000,
  "build_points",
  500,
  "use_demolished_state",
  false,
  "display_name",
  T({
    0,
    "Small Garden*"
  }),
  "display_name_pl",
  T({
    5266,
    "Small Gardens"
  }),
  "description",
  T({
    5151,
    "A recreational area with cultivated vegetation."
  }),
  "build_category",
  "Decorations",
  "display_icon",
  "UI/Icons/Buildings/small_garden.tga",
  "build_pos",
  3,
  "entity",
  "GardenNatural_01",
  "encyclopedia_image",
  "UI/Encyclopedia/SmallGarden.tga",
  "entity2",
  "GardenNatural_02",
  "entity3",
  "GardenNatural_03",
  "label1",
  "Decorations",
  "label2", "OutsideBuildings",
  "on_off_button",
  false,
  "prio_button",
  false,
  "comfort_increase",
  5000,
  "interest1",
  "interestRelaxation",
  "interest2",
  "interestExercise",
  "interest3",
  "interestPlaying",
  "max_visitors",
  1,
  "usable_by_children",
  true
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "SmartHome*",
  "template_class",
  "SmartHome",
  "construction_cost_Concrete",
  15000,
  "construction_cost_Electronics",
  10000,
  "show_decals_on_placement",
  true,
  "upgrade1_id",
  "SmartHome_HomeCollective",
  "upgrade1_display_name",
  T({
    5005,
    "Home Collective"
  }),
  "upgrade1_description",
  T({
    5272,
    "+<upgrade1_add_value_1> Service Comfort."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/home_collective_01.tga",
  "upgrade1_upgrade_cost_Polymers",
  5000,
  "upgrade1_mod_label_1",
  "SmartHome",
  "upgrade1_mod_prop_id_1",
  "service_comfort",
  "upgrade1_add_value_1",
  10,
  "maintenance_resource_type",
  "Electronics",
  "display_name",
  T({
    0,
    "Smart Complex*"
  }),
  "display_name_pl",
  T({
    7801,
    "Smart Complexes"
  }),
  "description",
  T({
    5273,
    "Provide a very comfortable living space for Colonists. Residents will recover additional Sanity when resting."
  }),
  "build_category",
  "Habitats",
  "display_icon",
  "UI/Icons/Buildings/smart homes.tga",
  "build_pos",
  4,
  "entity",
  "SmartHomeBig_01",
  "encyclopedia_image",
  "UI/Encyclopedia/SmartComplex.tga",
  "entity2",
  "SmartHomeBig_02",
  "entity3",
  "SmartHomeBig_03",
  "entity4",
  "SmartHomeBigDDE_01",
  "entitydlc4",
  "dde",
  "entity5",
  "SmartHomeBigDDE_02",
  "entitydlc5",
  "dde",
  "entity6",
  "SmartHomeBigDDE_03",
  "entitydlc6",
  "dde",
  "label1",
  "OutsideBuildings",
  "palettes",
  "Grocery",
  "demolish_sinking",
  range(15, 20),
  "demolish_debris",
  90,
  "freeze_heat",
  91,
  "electricity_consumption",
  4000,
  "sanity_change",
  5000,
  "service_comfort",
  70000,
  "comfort_increase",
  5000,
  "capacity",
  12,
  "sanity_increase",
  5000
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "SmartHome_Small*",
  "template_class",
  "SmartHome",
  "construction_cost_Concrete",
  5000,
  "construction_cost_Electronics",
  3000,
  "build_points",
  3000,
  "show_decals_on_placement",
  true,
  "upgrade1_id",
  "SmartHome_HomeCollective",
  "upgrade1_display_name",
  T({
    5005,
    "Home Collective"
  }),
  "upgrade1_description",
  T({
    5006,
    "+<upgrade1_add_value_1> Service Comfort."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/home_collective_01.tga",
  "upgrade1_upgrade_cost_Polymers",
  2000,
  "upgrade1_mod_label_1",
  "SmartHome_Small",
  "upgrade1_mod_prop_id_1",
  "service_comfort",
  "upgrade1_add_value_1",
  10,
  "maintenance_resource_type",
  "Electronics",
  "maintenance_resource_amount",
  500,
  "display_name",
  T({0, "Smart Home*"}),
  "display_name_pl",
  T({
    5270,
    "Smart Homes"
  }),
  "description",
  T({
    5271,
    "Provides a very comfortable living space for Colonists. Residents will recover additional Sanity when resting."
  }),
  "build_category",
  "Habitats",
  "display_icon",
  "UI/Icons/Buildings/smart_home.tga",
  "build_pos",
  3,
  "entity",
  "SmartHomeSmall_02",
  "encyclopedia_image",
  "UI/Encyclopedia/SmartHome.tga",
  "entity2",
  "SmartHomeSmall",
  "entity3",
  "SmartHomeSmallDDE_02",
  "entitydlc3",
  "dde",
  "entity4",
  "SmartHomeSmallDDE",
  "entitydlc4",
  "dde",
  "label1",
  "OutsideBuildings",
  "demolish_sinking",
  range(10, 20),
  "demolish_debris",
  80,
  "freeze_heat",
  91,
  "electricity_consumption",
  2000,
  "sanity_change",
  5000,
  "service_comfort",
  70000,
  "comfort_increase",
  5000,
  "capacity",
  4,
  "sanity_increase",
  5000
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "Spacebar*",
  "template_class",
  "Spacebar",
  "construction_cost_Concrete",
  15000,
  "construction_cost_Metals",
  5000,
  "build_points",
  5000,
  "upgrade1_id",
  "Spacebar_ServiceBots",
  "upgrade1_display_name",
  T({
    5020,
    "Service Bots"
  }),
  "upgrade1_description",
  T({
    5279,
    "This building no longer requires Workers and operates at <upgrade1_add_value_2> Performance."
  }),
  "upgrade1_icon",
  "UI/Icons/Upgrades/service_bots_01.tga",
  "upgrade1_upgrade_cost_Electronics",
  10000,
  "upgrade1_mod_prop_id_1",
  "automation",
  "upgrade1_add_value_1",
  1,
  "upgrade1_mod_prop_id_2",
  "auto_performance",
  "upgrade1_add_value_2",
  100,
  "upgrade1_mod_prop_id_3",
  "max_workers",
  "upgrade1_mul_value_3",
  -100,
  "maintenance_resource_type",
  "Concrete",
  "display_name",
  T({0, "Spacebar*"}),
  "display_name_pl",
  T({5281, "Spacebars"}),
  "description",
  T({
    5282,
    "Provides space for R&R and fancy cocktails."
  }),
  "build_category",
  "Dome Services",
  "display_icon",
  "UI/Icons/Buildings/spacebar.tga",
  "entity",
  "Spacebar",
  "encyclopedia_image",
  "UI/Encyclopedia/Spacebar.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "SpaceBar",
  "demolish_sinking",
  range(0, 0),
  "demolish_debris",
  80,
  "electricity_consumption",
  2000,
  "service_comfort",
  60000,
  "comfort_increase",
  15000,
  "interest1",
  "interestRelaxation",
  "interest2",
  "interestDrinking",
  "interest3",
  "interestSocial",
  "max_visitors",
  10,
  "enabled_shift_3",
  false,
  "max_workers",
  2
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "Statue*",
  "template_class",
  "Service",
  "construction_cost_Concrete",
  1000,
  "build_points",
  500,
  "use_demolished_state",
  false,
  "display_name",
  T({0, "Statue*"}),
  "display_name_pl",
  T({5284, "Statues"}),
  "description",
  T({
    5285,
    "\"In honor of the Founders of Mars.\""
  }),
  "build_category",
  "Decorations",
  "display_icon",
  "UI/Icons/Buildings/statue.tga",
  "build_pos",
  11,
  "entity",
  "GardenStatue_01",
  "encyclopedia_image",
  "UI/Encyclopedia/Statue.tga",
  "entity2",
  "GardenStatue_02",
  "label1",
  "Decorations",
  "label2", "OutsideBuildings",
  "on_off_button",
  false,
  "prio_button",
  false,
  "comfort_increase",
  5000,
  "interest1",
  "interestRelaxation",
  "interest2",
  "interestExercise",
  "interest3",
  "interestPlaying",
  "max_visitors",
  1,
  "usable_by_children",
  true
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "GardenStone*",
  "template_class",
  "Service",
  "construction_cost_Concrete",
  4000,
  "build_points",
  1000,
  "use_demolished_state",
  false,
  "display_name",
  T({
    0,
    "Stone Garden*"
  }),
  "display_name_pl",
  T({
    5291,
    "Stone Gardens"
  }),
  "description",
  T({
    5292,
    "A tastefully arranged stone garden, following strict Zen rules."
  }),
  "build_category",
  "Decorations",
  "display_icon",
  "UI/Icons/Buildings/stone_garden.tga",
  "build_pos",
  7,
  "entity",
  "GardenStone",
  "encyclopedia_image",
  "UI/Encyclopedia/StoneGarden.tga",
  "label1",
  "Decorations",
  "label2", "OutsideBuildings",
  "on_off_button",
  false,
  "prio_button",
  false,
  "comfort_increase",
  5000,
  "interest1",
  "interestRelaxation",
  "interest2",
  "interestExercise",
  "interest3",
  "interestPlaying",
  "max_visitors",
  3,
  "usable_by_children",
  true
}),
PlaceObj("ModItemBuildingTemplate", {
  "name",
  "WaterReclamationSystem*",
  "template_class",
  "WaterReclamationSpire",
  "construction_cost_Concrete",
  50000,
  "construction_cost_Polymers",
  10000,
  "construction_cost_MachineParts",
  5000,
  "build_points",
  30000,
  "require_prefab",
  true,
  "is_tall",
  true,
  --"dome_spot", "Spire",
  "achievement",
  "FirstDomeSpire",
  "maintenance_resource_type",
  "MachineParts",
  "maintenance_resource_amount",
  3000,
  "display_name",
  T({
    0,
    "Water Reclamation System*"
  }),
  "display_name_pl",
  T({
    5308,
    "Water Reclamation Systems"
  }),
  "description",
  T({
    5309,
    "Recycles up to 70% of the Water used in the Dome."
  }),
  "build_category",
  "Dome Spires",
  "display_icon",
  "UI/Icons/Buildings/water_reclamation.tga",
  "build_pos",
  3,
  "entity",
  "WaterReclamation",
  "encyclopedia_image",
  "UI/Encyclopedia/WaterReclamationSystem.tga",
  "label1",
  "OutsideBuildings",
  "palettes",
  "WaterReclamation",
  "demolish_sinking",
  range(0, 0),
  "demolish_tilt_angle",
  range(0, 0),
  "max_workers",
  2
}),

}
