function ChoGGi.BreakThroughTechsPerGameToggle()
  if const.BreakThroughTechsPerGame == 26 then
    const.BreakThroughTechsPerGame = ChoGGi.Consts.BreakThroughTechsPerGame
  else
    const.BreakThroughTechsPerGame = 26
  end
  ChoGGi.CheatMenuSettings.BreakThroughTechsPerGame = const.BreakThroughTechsPerGame
  ChoGGi.WriteSettings()
  ChoGGi.MsgPopup("S M R T",
   "Research","UI/Icons/Notifications/research.tga"
  )
end

function ChoGGi.ResearchEveryMystery()
  GrantTech("BlackCubesDisposal")
  GrantTech("AlienDiggersDestruction")
  GrantTech("AlienDiggersDetection")
  GrantTech("XenoExtraction")
  GrantTech("RegolithExtractor")
  GrantTech("PowerDecoy")
  GrantTech("Xeno-Terraforming")
  GrantTech("DreamSimulation")
  GrantTech("NumberSixTracing")
  GrantTech("DefenseTower")
  GrantTech("SolExploration")
  GrantTech("WildfireCure")
  ChoGGi.MsgPopup("Unleash your inner Black Monolith",
    "Research","UI/Icons/Notifications/research.tga"
  )
end

function ChoGGi.UnlockEveryBreakthrough()
  DiscoverTech("ConstructionNanites")
  DiscoverTech("HullPolarization")
  DiscoverTech("ProjectPhoenix")
  DiscoverTech("SoylentGreen")
  DiscoverTech("NeuralEmpathy")
  DiscoverTech("RapidSleep")
  DiscoverTech("ThePositronicBrain")
  DiscoverTech("SafeMode")
  DiscoverTech("HiveMind")
  DiscoverTech("SpaceRehabilitation")
  DiscoverTech("WirelessPower")
  DiscoverTech("PrintedElectronics")
  DiscoverTech("CoreMetals")
  DiscoverTech("CoreWater")
  DiscoverTech("CoreRareMetals")
  DiscoverTech("SuperiorCables")
  DiscoverTech("SuperiorPipes")
  DiscoverTech("AlienImprints")
  DiscoverTech("NocturnalAdaptation")
  DiscoverTech("GeneSelection")
  DiscoverTech("MartianDiet")
  DiscoverTech("EternalFusion")
  DiscoverTech("SuperconductingComputing")
  DiscoverTech("NanoRefinement")
  DiscoverTech("ArtificialMuscles")
  DiscoverTech("InspiringArchitecture")
  DiscoverTech("GiantCrops")
  DiscoverTech("NeoConcrete")
  DiscoverTech("AdvancedDroneDrive")
  DiscoverTech("DryFarming")
  DiscoverTech("MartianSteel")
  DiscoverTech("VectorPump")
  DiscoverTech("Superfungus")
  DiscoverTech("HypersensitivePhotovoltaics")
  DiscoverTech("FrictionlessComposites")
  DiscoverTech("ZeroSpaceComputing")
  DiscoverTech("MultispiralArchitecture")
  DiscoverTech("MagneticExtraction")
  DiscoverTech("SustainedWorkload")
  DiscoverTech("ForeverYoung")
  DiscoverTech("MartianbornIngenuity")
  DiscoverTech("CryoSleep")
  DiscoverTech("Cloning")
  DiscoverTech("GoodVibrations")
  DiscoverTech("DomeStreamlining")
  DiscoverTech("PrefabCompression")
  DiscoverTech("ExtractorAI")
  DiscoverTech("ServiceBots")
  DiscoverTech("OverchargeAmplification")
  DiscoverTech("PlutoniumSynthesis")
  DiscoverTech("InterplanetaryLearning")
  DiscoverTech("Vocation-Oriented Society")
  DiscoverTech("PlasmaRocket")
  DiscoverTech("AutonomousHubs")
  DiscoverTech("FactoryAutomation")
  ChoGGi.MsgPopup("Unleash your inner Black Monolith",
    "Research","UI/Icons/Notifications/research.tga"
  )
end

function ChoGGi.ResearchEveryBreakthrough()
  GrantTech("ConstructionNanites")
  GrantTech("HullPolarization")
  GrantTech("ProjectPhoenix")
  GrantTech("SoylentGreen")
  GrantTech("NeuralEmpathy")
  GrantTech("RapidSleep")
  GrantTech("ThePositronicBrain")
  GrantTech("SafeMode")
  GrantTech("HiveMind")
  GrantTech("SpaceRehabilitation")
  GrantTech("WirelessPower")
  GrantTech("PrintedElectronics")
  GrantTech("CoreMetals")
  GrantTech("CoreWater")
  GrantTech("CoreRareMetals")
  GrantTech("SuperiorCables")
  GrantTech("SuperiorPipes")
  GrantTech("AlienImprints")
  GrantTech("NocturnalAdaptation")
  GrantTech("GeneSelection")
  GrantTech("MartianDiet")
  GrantTech("EternalFusion")
  GrantTech("SuperconductingComputing")
  GrantTech("NanoRefinement")
  GrantTech("ArtificialMuscles")
  GrantTech("InspiringArchitecture")
  GrantTech("GiantCrops")
  GrantTech("NeoConcrete")
  GrantTech("AdvancedDroneDrive")
  GrantTech("DryFarming")
  GrantTech("MartianSteel")
  GrantTech("VectorPump")
  GrantTech("Superfungus")
  GrantTech("HypersensitivePhotovoltaics")
  GrantTech("FrictionlessComposites")
  GrantTech("ZeroSpaceComputing")
  GrantTech("MultispiralArchitecture")
  GrantTech("MagneticExtraction")
  GrantTech("SustainedWorkload")
  GrantTech("ForeverYoung")
  GrantTech("MartianbornIngenuity")
  GrantTech("CryoSleep")
  GrantTech("Cloning")
  GrantTech("GoodVibrations")
  GrantTech("DomeStreamlining")
  GrantTech("PrefabCompression")
  GrantTech("ExtractorAI")
  GrantTech("ServiceBots")
  GrantTech("OverchargeAmplification")
  GrantTech("PlutoniumSynthesis")
  GrantTech("InterplanetaryLearning")
  GrantTech("Vocation-Oriented Society")
  GrantTech("PlasmaRocket")
  GrantTech("AutonomousHubs")
  GrantTech("FactoryAutomation")
  ChoGGi.MsgPopup("Unleash your inner Black Monolith",
    "Research","UI/Icons/Notifications/research.tga"
  )
end

if ChoGGi.ChoGGiComp then
  AddConsoleLog("ChoGGi: MenuCheatsFunc.lua",true)
end
