return {
PlaceObj('ModItemBuildingTemplate', {
	'name', "Arcology+-",
	'template_class', "Arcology",
	'pin_rollover_hint', T{857446814135, --[[ModItemBuildingTemplate Arcology+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{926056041672, --[[ModItemBuildingTemplate Arcology+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 80000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "Arcology_HomeCollective",
	'upgrade1_display_name', T{886946997243, --[[ModItemBuildingTemplate Arcology+- upgrade1_display_name]] "Heimatgemeinschaft"},
	'upgrade1_description', T{919116524967, --[[ModItemBuildingTemplate Arcology+- upgrade1_description]] "+<upgrade1_add_value_1> Service-Komfort"},
	'upgrade1_icon', "UI/Icons/Upgrades/home_collective_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_mod_label_1', "Arcology",
	'upgrade1_mod_prop_id_1', "service_comfort",
	'upgrade1_add_value_1', 10,
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 4000,
	'display_name', T{507674958384, --[[ModItemBuildingTemplate Arcology+- display_name]] "Arkologie"},
	'display_name_pl', T{168209072014, --[[ModItemBuildingTemplate Arcology+- display_name_pl]] "Arkologie"},
	'description', T{962381671615, --[[ModItemBuildingTemplate Arcology+- description]] "Bietet Wohnraum für zahlreiche Kolonisten und gewährt viel Komfort."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/arcology.tga",
	'entity', "Arcology",
	'encyclopedia_image', "UI/Encyclopedia/Arcology.tga",
	'label1', "InsideBuildings",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(0, 0),
	'demolish_debris', 90,
	'spire_frame_entity', "ArcologyFrame",
	'electricity_consumption', 20000,
	'service_comfort', 60000,
	'comfort_increase', 4000,
	'capacity', 32,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "CloningVats+-",
	'template_class', "CloningVats",
	'pin_rollover_hint', T{779573366833, --[[ModItemBuildingTemplate CloningVats+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{497292653579, --[[ModItemBuildingTemplate CloningVats+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Metals', 50000,
	'construction_cost_Polymers', 20000,
	'construction_cost_Electronics', 10000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 3000,
	'display_name', T{174641942390, --[[ModItemBuildingTemplate CloningVats+- display_name]] "Klonbehälter"},
	'display_name_pl', T{418006033889, --[[ModItemBuildingTemplate CloningVats+- display_name_pl]] "Klonbehälter"},
	'description', T{251171237218, --[[ModItemBuildingTemplate CloningVats+- description]] "Erschafft im Laufe der Zeit Klone. Geklonte Kolonisten wachsen und altern doppelt so schnell."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/cloning_vats.tga",
	'build_pos', 4,
	'entity', "CloningVats",
	'encyclopedia_image', "UI/Encyclopedia/CloningVats.tga",
	'label1', "InsideBuildings",
	'palettes', "CloningVats",
	'demolish_sinking', range(15, 20),
	'demolish_tilt_angle', range(300, 720),
	'demolish_debris', 85,
	'electricity_consumption', 30000,
	'enabled_shift_2', false,
	'enabled_shift_3', false,
	'max_workers', 6,
	'specialist', "medic",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "HangingGardens+-",
	'template_class', "HangingGardens",
	'pin_rollover_hint', T{387893029819, --[[ModItemBuildingTemplate HangingGardens+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{918055644389, --[[ModItemBuildingTemplate HangingGardens+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 40000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'construction_site_applies_height_surfaces', true,
	'achievement', "FirstDomeSpire",
	'maintenance_resource_type', "Concrete",
	'maintenance_resource_amount', 4000,
	'display_name', T{442429190984, --[[ModItemBuildingTemplate HangingGardens+- display_name]] "Hängende Gärten"},
	'display_name_pl', T{179590437194, --[[ModItemBuildingTemplate HangingGardens+- display_name_pl]] "Hängende Gärten"},
	'description', T{324445947906, --[[ModItemBuildingTemplate HangingGardens+- description]] "Eine wunderschöne Parkanlage. Erhöht den Komfort aller Wohngebäude innerhalb der Kuppel."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/hanging_gardens.tga",
	'build_pos', 2,
	'entity', "HangingGardens",
	'dome_comfort', 30000,
	'encyclopedia_image', "UI/Encyclopedia/HangingGardens.tga",
	'label1', "InsideBuildings",
	'palettes', "Outside_10",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(0, 0),
	'water_consumption', 2000,
	'air_consumption', 0,
	'service_comfort', 100000,
	'comfort_increase', 15000,
	'interest1', "interestRelaxation",
	'interest2', "interestExercise",
	'interest3', "interestPlaying",
	'max_visitors', 20,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "MedicalCenter+-",
	'template_class', "MedicalCenter",
	'pin_rollover_hint', T{892700197825, --[[ModItemBuildingTemplate MedicalCenter+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{780277633911, --[[ModItemBuildingTemplate MedicalCenter+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 30000,
	'construction_cost_Metals', 30000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "MedicalCenter_HolographicScanner",
	'upgrade1_display_name', T{736079967840, --[[ModItemBuildingTemplate MedicalCenter+- upgrade1_display_name]] "Holografischer Scanner"},
	'upgrade1_description', T{292842550552, --[[ModItemBuildingTemplate MedicalCenter+- upgrade1_description]] "Erhöht die Geburtenrate innerhalb der Kuppel."},
	'upgrade1_icon', "UI/Icons/Upgrades/holographic_scanner_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_upgrade_cost_Electronics', 5000,
	'upgrade1_mod_target_1', "parent_dome",
	'upgrade1_mod_label_1', "Colonist",
	'upgrade1_mod_prop_id_1', "birth_comfort_modifier",
	'upgrade1_add_value_1', 30,
	'upgrade2_id', "MedicalCenter_RejuvenationTreatment",
	'upgrade2_display_name', T{759257059746, --[[ModItemBuildingTemplate MedicalCenter+- upgrade2_display_name]] "Verjüngungskur"},
	'upgrade2_description', T{284573166404, --[[ModItemBuildingTemplate MedicalCenter+- upgrade2_description]] "Erhöht den Service-Komfort. Kolonisten können ihn zur Entspannung nutzen."},
	'upgrade2_icon', "UI/Icons/Upgrades/rejuvenation_treatment_01.tga",
	'upgrade2_upgrade_cost_Polymers', 10000,
	'upgrade2_mod_label_1', "MedicalCenter",
	'upgrade2_mod_prop_id_1', "salvage_modifier",
	'upgrade2_mod_label_2', "MedicalCenter",
	'upgrade2_mod_prop_id_2', "service_comfort",
	'upgrade2_add_value_2', 15,
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 3000,
	'display_name', T{241110520612, --[[ModItemBuildingTemplate MedicalCenter+- display_name]] "Klinik"},
	'display_name_pl', T{230441551769, --[[ModItemBuildingTemplate MedicalCenter+- display_name_pl]] "Kliniken"},
	'description', T{638883971039, --[[ModItemBuildingTemplate MedicalCenter+- description]] "Besucher regenerieren Gesundheit und Besonnenheit, solange sie nicht hungern, dehydriert sind, erfrieren oder ersticken. Hat eine größere Kapazität und ist effektiver als die Krankenstation. Kuppeln mit medizinischen Einrichtungen benötigen weniger Komfort für Geburten."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/medical_center.tga",
	'build_pos', 7,
	'entity', "MedicalCenter",
	'encyclopedia_image', "UI/Encyclopedia/MedicalCenter.tga",
	'label1', "InsideBuildings",
	'label2', "MedicalBuilding",
	'palettes', "Outside_02",
	'demolish_sinking', range(10, 12),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 80,
	'electricity_consumption', 20000,
	'health_change', 50000,
	'sanity_change', 15000,
	'service_comfort', 70000,
	'comfort_increase', 15000,
	'interest1', "needMedical",
	'max_visitors', 10,
	'usable_by_children', true,
	'enabled_shift_3', false,
	'max_workers', 3,
	'specialist', "medic",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "NetworkNode+-",
	'template_class', "NetworkNode",
	'pin_rollover_hint', T{696926324126, --[[ModItemBuildingTemplate NetworkNode+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{101967795170, --[[ModItemBuildingTemplate NetworkNode+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 50000,
	'construction_cost_Metals', 50000,
	'construction_cost_Electronics', 20000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "NetworkNode_Amplify",
	'upgrade1_display_name', T{987760318360, --[[ModItemBuildingTemplate NetworkNode+- upgrade1_display_name]] "Verstärken"},
	'upgrade1_description', T{154983032326, --[[ModItemBuildingTemplate NetworkNode+- upgrade1_description]] "+<upgrade1_mul_value_2> % Leistung; + Verbrauch."},
	'upgrade1_icon', "UI/Icons/Upgrades/amplify_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_mod_label_1', "NetworkNode",
	'upgrade1_mod_prop_id_1', "electricity_consumption",
	'upgrade1_add_value_1', 20000,
	'upgrade1_mod_label_2', "NetworkNode",
	'upgrade1_mod_prop_id_2', "performance",
	'upgrade1_mul_value_2', 25,
	'maintenance_resource_type', "Electronics",
	'maintenance_resource_amount', 3000,
	'display_name', T{135350300133, --[[ModItemBuildingTemplate NetworkNode+- display_name]] "Netzwerkknoten"},
	'display_name_pl', T{232782632762, --[[ModItemBuildingTemplate NetworkNode+- display_name_pl]] "Netzwerkknoten"},
	'description', T{781055142838, --[[ModItemBuildingTemplate NetworkNode+- description]] "Erhöht die gesamte Forschungsleistung innerhalb der Kuppel."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/network_node.tga",
	'build_pos', 5,
	'entity', "NetworkNode",
	'encyclopedia_image', "UI/Encyclopedia/NetworkNode.tga",
	'label1', "InsideBuildings",
	'palettes', "NetworkNode",
	'demolish_sinking', range(5, 10),
	'demolish_tilt_angle', range(60, 300),
	'electricity_consumption', 20000,
	'enabled_shift_2', false,
	'enabled_shift_3', false,
	'max_workers', 6,
	'specialist', "scientist",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "Sanatorium+-",
	'template_class', "Sanatorium",
	'pin_rollover_hint', T{696513738281, --[[ModItemBuildingTemplate Sanatorium+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{901774446630, --[[ModItemBuildingTemplate Sanatorium+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 50000,
	'construction_cost_Metals', 20000,
	'construction_cost_Polymers', 10000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'upgrade1_id', "Sanatorium_BehavioralMelding",
	'upgrade1_display_name', T{301487317025, --[[ModItemBuildingTemplate Sanatorium+- upgrade1_display_name]] "Verhaltensbezogene Verschmelzung"},
	'upgrade1_description', T{886295366153, --[[ModItemBuildingTemplate Sanatorium+- upgrade1_description]] "Ersetzt bei Besuchern Schwächen durch Stärken."},
	'upgrade1_icon', "UI/Icons/Upgrades/behavioral_melding_01.tga",
	'upgrade1_upgrade_cost_Polymers', 10000,
	'upgrade1_upgrade_cost_Electronics', 10000,
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 2000,
	'display_name', T{635855798057, --[[ModItemBuildingTemplate Sanatorium+- display_name]] "Sanatorium"},
	'display_name_pl', T{157471845385, --[[ModItemBuildingTemplate Sanatorium+- display_name_pl]] "Sanatorien"},
	'description', T{734352037551, --[[ModItemBuildingTemplate Sanatorium+- description]] "Behandelt Kolonisten, um Schwächen mit fortschrittlichen und meist menschlichen Methoden zu heilen."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/sanatorium.tga",
	'build_pos', 7,
	'entity', "Sanatorium",
	'encyclopedia_image', "UI/Encyclopedia/Sanatorium.tga",
	'label1', "InsideBuildings",
	'palettes', "Sanatorium",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(300, 600),
	'electricity_consumption', 20000,
	'enabled_shift_1', false,
	'enabled_shift_3', false,
	'max_visitors', 4,
	'evaluation_points', 200,
	'trait1', "Gambler",
	'trait2', "Alcoholic",
	'trait3', "Glutton",
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "WaterReclamationSystem+-",
	'template_class', "WaterReclamationSpire",
	'pin_rollover_hint', T{574076110509, --[[ModItemBuildingTemplate WaterReclamationSystem+- pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{937349735157, --[[ModItemBuildingTemplate WaterReclamationSystem+- pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'construction_cost_Concrete', 50000,
	'construction_cost_Polymers', 10000,
	'construction_cost_MachineParts', 5000,
	'build_points', 30000,
	'require_prefab', true,
	'is_tall', true,
	'achievement', "FirstDomeSpire",
	'maintenance_resource_type', "MachineParts",
	'maintenance_resource_amount', 3000,
	'display_name', T{626634493883, --[[ModItemBuildingTemplate WaterReclamationSystem+- display_name]] "WRS"},
	'display_name_pl', T{995876065359, --[[ModItemBuildingTemplate WaterReclamationSystem+- display_name_pl]] "WRS"},
	'description', T{111914132800, --[[ModItemBuildingTemplate WaterReclamationSystem+- description]] "Verwertet 70 % des verbrauchten Wassers innerhalb der Kuppel wieder."},
	'build_category', "Dome Spires",
	'display_icon', "UI/Icons/Buildings/water_reclamation.tga",
	'build_pos', 3,
	'entity', "WaterReclamation",
	'encyclopedia_image', "UI/Encyclopedia/WaterReclamationSystem.tga",
	'label1', "InsideBuildings",
	'palettes', "WaterReclamation",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(0, 0),
	'max_workers', 2,
}),
}
