  BuildCategories = {
  {id = "Infrastructure", name = T({78, "Infrastructure"}), img = "UI/Icons/bmc_infrastructure.tga", highlight_img = "UI/Icons/bmc_infrastructure_shine.tga"}
  ,
  {id = "Power", name = T({79, "Power"}), img = "UI/Icons/bmc_power.tga", highlight_img = "UI/Icons/bmc_power_shine.tga"}
  ,
  {id = "Production", name = T({80, "Production"}), img = "UI/Icons/bmc_building_resources.tga", highlight_img = "UI/Icons/bmc_building_resources_shine.tga"}
  ,
  {id = "Life-Support", name = T({81, "Life Support"}), img = "UI/Icons/bmc_life_support.tga", highlight_img = "UI/Icons/bmc_life_support_shine.tga"}
  ,
  {id = "Storages", name = T({82, "Storages"}), img = "UI/Icons/bmc_building_storages.tga", highlight_img = "UI/Icons/bmc_building_storages_shine.tga"}
  ,
  {id = "Domes", name = T({83, "Domes"}), img = "UI/Icons/bmc_domes.tga", highlight_img = "UI/Icons/bmc_domes_shine.tga"}
  ,
  {id = "Habitats", name = T({84, "Homes, Education & Research"}), img = "UI/Icons/bmc_habitats.tga", highlight_img = "UI/Icons/bmc_habitats_shine.tga"}
  ,
  {id = "Dome Services", name = T({85, "Dome Services"}), img = "UI/Icons/bmc_dome_buildings.tga", highlight_img = "UI/Icons/bmc_dome_buildings_shine.tga"}
  ,
  {id = "Dome Spires", name = T({86, "Dome Spires"}), img = "UI/Icons/bmc_dome_spires.tga", highlight_img = "UI/Icons/bmc_dome_spires_shine.tga"}
  ,
  {id = "Decorations", name = T({87, "Decorations"}), img = "UI/Icons/bmc_decorations.tga", highlight_img = "UI/Icons/bmc_decorations_shine.tga"}
  ,
  {id = "Wonders", name = T({88, "Wonders"}), img = "UI/Icons/bmc_wonders.tga", highlight_img = "UI/Icons/bmc_wonders_shine.tga"}
  ,
  {id = "Hidden", name = T({1000155, "Hidden"}), img = "UI/Icons/bmc_placeholder.tga", highlight_img = "UI/Icons/bmc_placeholder_shine.tga"}
  ,
  {id = "HiddenX", name = T({1000155, "HiddenX"}), img = "UI/Icons/bmc_placeholder.tga", highlight_img = "UI/Icons/bmc_placeholder_shine.tga"}
  }

return {

PlaceObj("ModItemBuildingTemplate", {
  "name", "MirrorSphere*",
  "template_class", "MirrorSphereBuilding",
  "build_points", 0,
  "instant_build", true,
  "dome_forbidden", true,
  "can_cancel", false,
  "can_user_change_prio", false,
  --"can_demolish", false,
  "can_demolish", true,
  "display_name", "Mirror Sphere*",
  "display_name_pl","Mirror Spheres",
  "description", "A reflective sphere of unknown composition. Once you build it; you can't remove it...",
  "build_category", "HiddenX",
  "display_icon", "UI/Icons/Buildings/mirror_sphere.tga",
  "build_pos", 7,
  "entity", "MirrorSphereExcavation",
  "ip_template", "ipMirrorSphereBuilding",
  "encyclopedia_exclude", true,
  "on_off_button", false,
  "prio_button", false,
  --"indestructible", true
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "SupplyRocket*",
  "template_class", "SupplyRocket",
  "pin_rollover_hint", T({705, "<left_click> Land Rocket"}),
  "pin_rollover_hint_xbox", T({706, "<ButtonA> Land Rocket"}),
  "pin_obvious_blink", true,
  "construction_cost_Metals", 60000,
  "construction_cost_Electronics", 20000,
  "construction_entity", "RocketLandingSite",
  "build_points", 0,
  "instant_build", true,
  "can_rotate_during_placement", false,
  "dome_forbidden", true,
  "display_name", "Rocket*",
  "display_name_pl","Rockets",
  "description","Delivers cargo or Colonists to Mars. Commands nearby Drones. Contaminates nearby buildings with dust when landing and taking off. Requires <em>Fuel</em> for the return trip to Earth.",
  "build_category", "HiddenX",
  "display_icon", "UI/Icons/Buildings/rocket.tga",
  "build_pos", 7,
  "entity", "Rocket",
  "label1", "Spaceship",
  "on_off_button", false,
  --"indestructible", true,
  "exclude_from_lr_transportation", true,
  "max_storage_per_resource", 60000,
  "storable_resources", {"Concrete", "Metals", "Polymers", "Food", "Electronics", "MachineParts"},
  "starting_drones", 0,
  "launch_fuel", 60000,
  "max_export_storage", 30000
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "TradeRocket*",
  "template_class", "TradeRocket",
  "pin_rollover_hint", T({705, "<left_click> Land Rocket"}),
  "pin_rollover_hint_xbox", T({706, "<ButtonA> Land Rocket"}),
  "pin_obvious_blink", true,
  "construction_cost_Metals", 60000,
  "construction_cost_Electronics", 20000,
  "construction_entity", "RocketLandingSite",
  "build_points", 0,
  "instant_build", true,
  "can_rotate_during_placement", false,
  "dome_forbidden", true,
  "display_name","Rocket*",
  "display_name_pl","Rockets",
  "description", "Delivers cargo or Colonists to Mars. Commands nearby Drones. Contaminates nearby buildings with dust when landing and taking off. Requires <em>Fuel</em> for the return trip to Earth.",
  "build_category", "HiddenX",
  "display_icon", "UI/Icons/Buildings/rocket_trade.tga",
  "build_pos", 7,
  "entity", "Rocket",
  "encyclopedia_exclude", true,
  "label1", "Spaceship",
  "on_off_button", false,
  --"indestructible", true,
  "exclude_from_lr_transportation", true,
  "max_storage_per_resource", 60000,
  "storable_resources", {"Concrete", "Metals", "Polymers", "Food", "Electronics", "MachineParts"},
  "starting_drones", 0,
  "launch_fuel", 60000
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "RefugeeRocket*",
  "template_class", "RefugeeRocket",
  "pin_rollover_hint", T({705, "<left_click> Land Rocket"}),
  "pin_rollover_hint_xbox", T({706, "<ButtonA> Land Rocket"}),
  "pin_obvious_blink", true,
  "construction_cost_Metals", 60000,
  "construction_cost_Electronics", 20000,
  "construction_entity", "RocketLandingSite",
  "build_points", 0,
  "instant_build", true,
  "can_rotate_during_placement", false,
  "dome_forbidden", true,
  "display_name","Rocket*",
  "display_name_pl", "Rockets",
  "description", "Delivers cargo or Colonists to Mars. Commands nearby Drones. Contaminates nearby buildings with dust when landing and taking off. Requires <em>Fuel</em> for the return trip to Earth.",
  "build_category", "HiddenX",
  "display_icon", "UI/Icons/Buildings/rocket_trade.tga",
  "build_pos", 7,
  "entity", "Rocket",
  "encyclopedia_exclude", true,
  "label1", "Spaceship",
  "on_off_button", false,
  --"indestructible", true,
  "exclude_from_lr_transportation", true,
  "max_storage_per_resource", 60000,
  "storable_resources", {"Concrete", "Metals", "Polymers", "Food", "Electronics", "MachineParts"},
  "starting_drones", 0,
  "launch_fuel", 0
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "BlackCubeMonolith*",
  "template_class", "",
  "construction_cost_BlackCube", 284000,
  "build_points", 5000,
  "dome_forbidden", true,
  "can_cancel", false,
  "can_user_change_prio", false,
  --"hide_from_build_menu", true,
  --"can_demolish", false,
  "can_demolish", true,
  "display_name","Mega Monument*",
  "display_name_pl", "Mega Monuments",
  "description","A gigantic structure made of Black Cubes. Once you build it; you can't remove it...",
  "build_category", "Domes",
  "display_icon", "UI/Icons/Buildings/black_cube_monolith.tga",
  "build_pos", 0,
  "entity", "BlackCubeMonolith",
  "encyclopedia_exclude", true,
  "on_off_button", false,
  "prio_button", false,
  --"indestructible", true
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "BlackCubeDump*",
  "template_class", "BlackCubeDumpSite",
  "build_points", 0,
  "dome_forbidden", true,
  "display_name", "Cube Depot*",
  "display_name_pl","Cube Depots",
  "description", "A safe place to store Black Cubes.",
  "build_category", "Storages",
  "display_icon", "UI/Icons/Buildings/black_cube_dump_site.tga",
  "build_pos", 11,
  "entity", "StorageDepotSmall_09",
  "encyclopedia_exclude", true,
  "on_off_button", false,
  "prio_button", false,
  "max_amount_BlackCube", 81000
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "BlackCubeLargeMonument*",
  "template_class", "",
  "construction_cost_BlackCube", 126000,
  "build_points", 1000,
  "use_demolished_state", false,
  "display_name","Large Monument*",
  "display_name_pl", "Large Monuments",
  "description","A decorative monument created from the mysterious Black Cubes. Definitely not a place of worship.",
  "build_category", "Decorations",
  "display_icon", "UI/Icons/Buildings/black_cube_monument_large.tga",
  "build_pos", 14,
  "entity", "BlackCubeMonumentLarge",
  "encyclopedia_exclude", true,
  "on_off_button", false,
  "prio_button", false
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "StorageMysteryResource*",
  "template_class", "MysteryDepot",
  "pin_summary1", T({8111, "<resource(Stored_MysteryResource, MysteryResource)>"}),
  "build_points", 0,
  "instant_build", true,
  "dome_forbidden", true,
  "display_name", "Mystery Depot*",
  "display_name_pl", "Mystery Depot",
  "description","It\'s very mysterious.",
  "build_category", "Storages",
  "display_icon", "UI/Icons/Buildings/mystery_resource_storage.tga",
  "build_pos", 12,
  "entity", "StorageDepotSmall_10",
  "encyclopedia_exclude", true,
  "encyclopedia_image", "UI/Encyclopedia/MetalsDepot.tga",
  "on_off_button", false,
  "prio_button", false,
  "max_storage_per_resource", 180000,
  "max_x", 12,
  "storable_resources", {"MysteryResource"}
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "BlackCubeSmallMonument*",
  "template_class", "",
  "construction_cost_BlackCube", 42000,
  "build_points", 1000,
  "use_demolished_state", false,
  "display_name","Small Monument*",
  "display_name_pl","Small Monuments",
  "description", "A decorative monument created from the mysterious Black Cubes. Probably harmless.",
  "build_category", "Decorations",
  "display_icon", "UI/Icons/Buildings/black_cube_monument_small.tga",
  "build_pos", 13,
  "entity", "BlackCubeMonumentSmall",
  "encyclopedia_exclude", true,
  "on_off_button", false,
  "prio_button", false
}),

PlaceObj("ModItemBuildingTemplate", {
  "name", "PowerDecoy*",
  "template_class", "PowerDecoy",
  "construction_cost_Concrete", 10000,
  "construction_cost_Polymers", 5000,
  "construction_cost_Electronics", 5000,
  "build_points", 5000,
  "dome_forbidden", true,
  "display_name", "Power Decoy*",
  "display_name_pl","Power Decoys",
  "description", "Traps a single Mirror Sphere.",
  "build_category", "Infrastructure",
  "display_icon", "UI/Icons/Buildings/power_decoy.tga",
  "build_pos", 13,
  "entity", "PowerDecoy",
  "encyclopedia_exclude", true,
  "label1", "OutsideBuildings",
  "palettes", "PowerDecoy",
  "electricity_consumption", 10000
}),

--[[ VERY BROKEN, this will break mouse selection and keyboard controls
PlaceObj("ModItemBuildingTemplate", {
  "name", "RocketLandingSite*",
  "template_class", "RocketLandingSite",
  "construction_entity", "RocketLandingSite",
  "build_points", 0,
  "instant_build", true,
  "is_tall", true,
  "dome_forbidden", true,
  "force_extend_bb_during_placement_checks", 1000,
  "can_user_change_prio", false,
  "display_name", "Rocket Landing Site*",
  "display_name_pl", "Rocket Landing Sites",
  "description", "The landing site of a Rocket.",
  "build_category", "HiddenX",
  "display_icon", "UI/Icons/Buildings/placeholder.tga",
  "build_pos", 7,
  "entity", "RocketLandingSite",
  "encyclopedia_exclude", true,
  --"indestructible", true
}),
--]]

}
