return {
PlaceObj('ModItemBuildingTemplate', {
	'name', "Oval Dome",
	'comment', "Place for 2 Dome Spires ;)",
	'template_class', "DomeOval",
	'pin_rollover_hint', T{959661054126, --[[ModItemBuildingTemplate Oval Dome pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Auswählen"},
	'pin_rollover_hint_xbox', T{270716986977, --[[ModItemBuildingTemplate Oval Dome pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> Ansehen"},
	'pin_summary1', T{388891550812, --[[ModItemBuildingTemplate Oval Dome pin_summary1]] "<GetColonistCount><image UI/Icons/res_colonist.tga 800>"},
	'pin_on_start', true,
	'construction_cost_Concrete', 150000,
	'construction_cost_Metals', 150000,
	'construction_cost_Polymers', 100000,
	'construction_entity', "DomeOvalConstruction",
	'build_points', 80000,
	'is_tall', true,
	'construction_site_applies_height_surfaces', true,
	'dome_forbidden', true,
	'achievement', "FirstDome",
	'maintenance_resource_type', "Polymers",
	'maintenance_resource_amount', 4000,
	'display_name', T{406364966233, --[[ModItemBuildingTemplate Oval Dome display_name]] "Ovale Kuppel"},
	'display_name_pl', T{215552202949, --[[ModItemBuildingTemplate Oval Dome display_name_pl]] "Ovale Kuppeln"},
	'description', T{574478235774, --[[ModItemBuildingTemplate Oval Dome description]] "Ein längliches Kuppeldesign, das Platz für zwei Spitzen bietet."},
	'build_category', "Domes",
	'display_icon', "UI/Icons/Buildings/polymer_dome.tga",
	'build_pos', 4,
	'entity', "DomeOval",
	'dome_comfort', 60000,
	'encyclopedia_image', "UI/Encyclopedia/OvalDome.tga",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 0,
	'electricity_consumption', 40000,
	'water_consumption', 2000,
	'air_consumption', 2000,
}),
}
